### ISSUE TITLE
Ubuntu 环境下，QR code扫描不出来

### ISSUE THREAD

**Issue by Qxxxx** [NanmiCoder/MediaCrawler#1]
在linux系统下，QR code显示之后，扫描完全没有反映。
![image](https://github.com/NanmiCoder/MediaCrawler/assets/10084303/c93efa8e-33b1-4eea-bc9c-fbb96e72176f)

**Comment by Qxxxx** [comment]
解决了，原来是背景黑色，导致二维码一部分识别不出来

**Comment by stay-leave** [comment]
老哥怎么解决的？求教

**Comment by NanmiCoder** [comment]
这个问题刚刚修复了，在二维码周围加了一个白色背景边框，再试试~
https://github.com/NanmiCoder/MediaCrawler/blob/320ebf3a64b9143e541c8612efbfaae025008295/utils.py#L40

**Comment by NanmiCoder** [comment]
已修复，在二维码周围添加了边框。
https://github.com/NanmiCoder/MediaCrawler/blob/320ebf3a64b9143e541c8612efbfaae025008295/utils.py#L40-L44

**Comment by stay-leave** [comment]
好的，多谢大佬
