### ISSUE TITLE
docker中运行服务报错

### ISSUE THREAD

**Issue by lanlangdeai** [NanmiCoder/MediaCrawler#101]
在docker环境中,使用扫码方式登录小红书发生错误:display-im6.q16: unable to open X server `' @ error/display.c/DisplayImageCommand/412

执行的命令:python main.py --platform xhs --lt qrcode

**Comment by NanmiCoder** [comment]
提供下 Dockerfile，另外如果要跑在 docker 中，建议使用 cookies 的方法登录

**Comment by NanmiCoder** [comment]
在 docker 中建议使用 cookies 登录，不要使用二维码的方式，因为显示二维码的代码不确定在其他系统中可用（linux）
