### ISSUE TITLE
我希望只在登录时使用playwright，爬取时可以关闭playwright的窗口，可以从哪里入手呢，能不能提供一些思路。

### ISSUE THREAD

**Issue by yaohongfenglove** [NanmiCoder/MediaCrawler#103]
当前程序，当登录成功后，playwright启动的窗口不能关闭掉，因为post和get时需要header，而header需要从playwright获取。
playwright启动的窗口占用很大内存，哪怕是headless模式， **我希望只在登录时使用playwright，爬取时可以关闭playwright的窗口，可以从哪里入手呢，能不能提供一些思路。** 且playwright在登录和爬取中解耦后，爬取的程序就可以跑在非Ubuntu上了

**Comment by Yi-Lyu** [comment]
资讯类似问题，我在 ubuntu server 上运行，弹不出二维码，是因为必须要有 gui 的窗口才可以嘛？

**Comment by NanmiCoder** [comment]
> 当前程序，当登录成功后，playwright启动的窗口不能关闭掉，因为post和get时需要header，而header需要从playwright获取。 playwright启动的窗口占用很大内存，哪怕是headless模式， **我希望只在登录时使用playwright，爬取时可以关闭playwright的窗口，可以从哪里入手呢，能不能提供一些思路。** 且playwright在登录和爬取中解耦后，爬取的程序就可以跑在非Ubuntu上了

目前仓库的小红书是强依赖playwright，其他平台 的爬虫可以在登录成功后，将headers（cookie，useragent）传递给对应的client端，clien端移除playwright的依赖就行了

**Comment by NanmiCoder** [comment]
> 资讯类似问题，我在 ubuntu server 上运行，弹不出二维码，是因为必须要有 gui 的窗口才可以嘛？

linux没有可视化界面的系统不要使用二维码登录，使用cookies的方式

**Comment by xiaoqdu** [comment]
小红书，可以不强依赖playwright.  我也希望在登录的时候，依赖Playwright,将Cookies保存下来， 在爬取的时候，通过Cookies方式爬取，不行，一直提示406错误。

**Comment by yaohongfenglove** [comment]
姚宏锋已收到您的来信，谢谢。

**Comment by yaohongfenglove** [comment]
姚宏锋已收到您的来信，谢谢。

**Comment by hjmhjms** [comment]
> 小红书，可以不强依赖playwright. 我也希望在登录的时候，依赖Playwright,将Cookies保存下来， 在爬取的时候，通过Cookies方式爬取，不行，一直提示406错误。

cookie模式，我也遇到406， 应该怎么处理。是不是认为cookies模式行不通？

**Comment by abearxiong** [comment]
> cookie模式，我也遇到406， 应该怎么处理。是不是认为cookies模式行不通？

 因为每次小红书都要做签名，不是只有cookie，playwritght要一直启动着一只配签名
