### ISSUE TITLE
CRAWLER_MAX_NOTES_COUNT设置太小总报错

### ISSUE THREAD

**Issue by cl165** [NanmiCoder/MediaCrawler#106]
CRAWLER_MAX_NOTES_COUNT=10，总是报错：
![image](https://github.com/NanmiCoder/MediaCrawler/assets/6203863/735c28cf-3532-479f-bf7f-7f3a82f70b75)
CRAWLER_MAX_NOTES_COUNT = 100，就没问题了
什么原因？

**Comment by NanmiCoder** [comment]
最小是20，分页最小数量，这一天后续我在配置文件中标明
