### ISSUE TITLE
哔哩哔哩 video_id 识别问题（AV -> BV号转换）

### ISSUE THREAD

**Issue by karmalet** [NanmiCoder/MediaCrawler#107]
大佬好，
[b站视频ID号变了，](https://www.bilibili.com/read/cv5247479/)
MediaCrawler 中 BILI_SPECIFIED_ID_LIST 貌似不支持BV视频号，怎么能解决该问题？

例如，下面设置不管用
BILI_SPECIFIED_ID_LIST = [
    "17W411U7bi",
    "1hi4y1s7xL", #这个视频消失了
]

谢谢！

**Comment by NanmiCoder** [comment]
你的这些ID，提供下ID对应落地视频链接，我看下

**Comment by karmalet** [comment]
[https://www.bilibili.com/video/BV17W411U7bi](url)
[https://www.bilibili.com/video/BV1Yq4y1F7Dq](url)
非常感谢！

**Comment by NanmiCoder** [comment]
我印象里BILI_SPECIFIED_ID_LIST直接填写：BV17W411U7bi 是可以的，BV开头

**Comment by karmalet** [comment]
谢谢您的答复
一开始貌似顺利爬虫，MediaCrawler INFO [get_comments] begin get video_id: BV1d54y1g7db comments ...
之后碰到访问权限问题：MediaCrawler ERROR [get_comments] get video_id: BV1d54y1g7db comment error: 访问权限不足
怀疑我的配置中COOKIES影响到访问权限，所以删掉了COOKIES变量，还是出现同样的问题。
设置到LOGIN_TYPE = "qrcode"，也不会弹出qrcode。我在哪儿搞错的？谢谢大佬！

**Comment by NanmiCoder** [comment]
我试了一下你提供的这个视频ID，应该是属于评论很多的那种，原来的评论获取逻辑是获取所有的评论之后再返回到调用方，现在已经修改为了边拉评论边保存，更新下最新代码试试～

**Comment by karmalet** [comment]
谢谢大佬，完美解决了！
