### ISSUE TITLE
抓取的图片、视频链接合集怎么打开？

### ISSUE THREAD

**Issue by Danny0802** [NanmiCoder/MediaCrawler#108]
笔记的图片合集或者视频抓取下来后，在表格中是一个链接合集，如下
https://sns-img-qc.xhscdn.com/c2309cb8-fe5d-79bf-a8a5-90bb2b1ecca0,https://sns-img-qc.xhscdn.com/19a319ba-178a-f909-53f2-93b2d8f77789,https://sns-img-qc.xhscdn.com/862e3d3c-8f8a-81a6-f9b1-2e5289eb3813,https://sns-img-qc.xhscdn.com/12f59638-9e8c-c13f-3645-5e954197c4dd,https://sns-img-qc.xhscdn.com/0f27f47f-d929-e20c-ca48-2cad59ef0301,https://sns-img-qc.xhscdn.com/3047d3e5-b17c-1920-da1f-7b69ee65ba34,https://sns-img-qc.xhscdn.com/01d264c3-ebfb-c7e5-e18b-53d296ed4df8  这些链接单独访问后会下载一个文件，但是很多文件下载后打不开，请问怎么才能打开呢？

**Comment by NanmiCoder** [comment]
最新的[commit](https://github.com/NanmiCoder/MediaCrawler/commit/fe073801f8e1e711e6bbe744f406b0fd0a0ce69e)已告知小红书图片下载方法
<img width="947" alt="image" src="https://github.com/NanmiCoder/MediaCrawler/assets/47178017/9119b742-c327-4bfd-8ece-1310eb5cb21b">

**Comment by Tsai5277** [comment]
> 最新的[commit](https://github.com/NanmiCoder/MediaCrawler/commit/fe073801f8e1e711e6bbe744f406b0fd0a0ce69e)已加上小红书图片下载方法 <img alt="image" width="947" src="https://private-user-images.githubusercontent.com/47178017/293968250-9119b742-c327-4bfd-8ece-1310eb5cb21b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTI1MjMsIm5iZiI6MTcwNDY5MjIyMywicGF0aCI6Ii80NzE3ODAxNy8yOTM5NjgyNTAtOTExOWI3NDItYzMyNy00YmZkLThlY2UtMTMxMGViNWNiMjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA1MzcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMDk2MTlhMzg5NTdlMzY3OWI1ZWZmOTg0ZTk2Zjg0YWRhNmE5YjkyMzVmMjI4MDQ3ZDg3ZjliZDA2Zjg4MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A0YxcXQi2H20TELdwkSBOsB-2Phds1EDyhSlhZ8gjrE">

你好，请问是怎么想到这么解决的呢，我最近也遇到这个问题了，但是没有解决思路
