### ISSUE TITLE
抖音视频爬取时筛选设置无效

### ISSUE THREAD

**Issue by ScarlettSun9** [NanmiCoder/MediaCrawler#109]
抖音检索视频后结果可以按照排序依据、发布时间等进行筛选，目前筛选变量修改后结果没有变化，依然是网站默认检索结果。

field.py 中 3个class: 

![image](https://github.com/NanmiCoder/MediaCrawler/assets/53145308/5a594060-a362-4da0-82c3-3726a915d15c)

在 client.py 中修改后爬取结果无变化：

![image](https://github.com/NanmiCoder/MediaCrawler/assets/53145308/f0486bb3-8f8f-4707-978d-f23920dff82d)

**Comment by NanmiCoder** [comment]
已修复
