### ISSUE TITLE
小红书二维码登入超时

### ISSUE THREAD

**Issue by a43460588** [NanmiCoder/MediaCrawler#111]
![issues](https://github.com/NanmiCoder/MediaCrawler/assets/9876959/495fc2f9-1048-460f-8974-64cb50772a13)
小红书扫描二维码登入时，手机端显示成功，但是python这边最终超时也没登进去

**Comment by NanmiCoder** [comment]
拉取最新代码试试，感觉是登录过程中出现了二维码

**Comment by a43460588** [comment]
的确，换成有头模式查看，页面出现了验证码
