### ISSUE TITLE
csv模式建议

### ISSUE THREAD

**Issue by Cyiming** [NanmiCoder/MediaCrawler#117]
我拿b站举例

1、爬完一个视频 再爬一遍会在后面增加一遍评论也就是两遍  能不能是更新模式 重复不动 新的新增

2、我发现文件命名按照日期 不是按照视频划分的 这就导致不同视频评论放在一个文件里混在一起 希望能有模式一个视频一个文件评论

**Comment by NanmiCoder** [comment]
1、CSV如果要做增量更新比较麻烦，请存入DB实现，DB的逻辑中有判重。  
2、第二个需求同理，请用DB实现，能做到分类。

**Comment by NanmiCoder** [comment]
存数据用MySQL或PgSQL都可以

yiming ***@***.***>于2024年1月16日 周二20:29写道：

**Comment by Cyiming** [comment]
> MySQL

麻烦帮我看看哪弄的不对

1、我安装了mysql，并设置了密码
![image](https://github.com/NanmiCoder/MediaCrawler/assets/45073586/5fa04e46-e997-4478-a8ad-9475aab776d0)
![image](https://github.com/NanmiCoder/MediaCrawler/assets/45073586/0cfb116e-3c86-4965-adcd-1380f2d064d3)
2、修改db.py的123456的密码换成我的密码
3、运行db.py
4、运行main
5、报错tortoise.exceptions.DBConnectionError: Can't connect to MySQL server: {'host': 'localhost', 'port': 3306, 'user': 'root', 'db': 'media_crawler', 'autocommit': True, 'charset': 'utf8mb4', 'minsize': 1, 'maxsize': 5, 'sql_mode': 'STRICT_TRANS_TABLES'}

**Comment by NanmiCoder** [comment]
执行`python db.py` 初始化数据库了吗

**Comment by Cyiming** [comment]
> 执行`python db.py` 初始化数据库了吗

执行了 第三步

**Comment by NanmiCoder** [comment]
加QQ群吧，这里依一来一回的效率低

**Comment by pfeducode** [comment]
有群吗，拉我一下
