### ISSUE TITLE
将playwright的逻辑从爬虫业务逻辑中抽离出去

### ISSUE THREAD

**Issue by NanmiCoder** [NanmiCoder/MediaCrawler#119]
目前的代码实现是强依赖playwright的，导致在linux系统上部署不方便，计划将playwright抽离出去，单独提供浏览器环境的功能。

**Comment by NanmiCoder** [comment]
- [ ] 抽离playwright，给个平台的API Client实现移除playwright的浏览器对象传递
- [ ] 包装playwright成一个服务，提供给拆离后的MediaCrawler调用

**Comment by hopemeng** [comment]
大佬，windows11系统，我在venv中直接执行python main.py可以成功，但是打包可执行程序后执行就报错了😂
![image](https://github.com/NanmiCoder/MediaCrawler/assets/20451004/73b75da0-3053-4936-8f7d-f015e172daf5)
![image](https://github.com/NanmiCoder/MediaCrawler/assets/20451004/c0accbf4-7c3a-41ee-b732-b14cda07f38b)

**Comment by NanmiCoder** [comment]
pyinstaller安装到虚拟环境中再打包，这个错误是你当前的python环境没有安装playwrigth

**Comment by hopemeng** [comment]
@NanmiCoder 我是已经在venv虚拟环境安装了pyinstaller
![image](https://github.com/NanmiCoder/MediaCrawler/assets/20451004/8219b99b-0f47-4765-9300-2a1b5ed77f5f)
然后pyinstaller --onefile main.py
![image](https://github.com/NanmiCoder/MediaCrawler/assets/20451004/f4d9e054-947b-4d10-8173-b1c0848a20aa)
![image](https://github.com/NanmiCoder/MediaCrawler/assets/20451004/0ea70ab9-0f97-4744-9e64-ec77553ebda6)
直接运行没问题
![image](https://github.com/NanmiCoder/MediaCrawler/assets/20451004/998ea125-c5bd-45ad-ac5e-5ce823d501da)
运行可执行文件出错

**Comment by Coaixy** [comment]
> @NanmiCoder 我是已经在venv虚拟环境安装了pyinstaller ![image](https://private-user-images.githubusercontent.com/20451004/301003845-8219b99b-0f47-4765-9300-2a1b5ed77f5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MzU4ODAsIm5iZiI6MTcxMDYzNTU4MCwicGF0aCI6Ii8yMDQ1MTAwNC8zMDEwMDM4NDUtODIxOWI5OWItMGY0Ny00NzY1LTkzMDAtMmExYjVlZDc3ZjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDAwMzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMTlkNDA2ZDFlMDNhOTgyOGQ4OGVhMzUxM2FmMDgwNzhhMmQ4NzFiN2MyMDIwMTA4NDNhMGQ4Y2ZlZDcyMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1uQ_WC9WEzYQ4SbLF-Y6At8EBrF_EWVM6jSWXbxqA8I) 然后pyinstaller --onefile main.py ![image](https://private-user-images.githubusercontent.com/20451004/301004368-f4d9e054-947b-4d10-8173-b1c0848a20aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MzU4ODAsIm5iZiI6MTcxMDYzNTU4MCwicGF0aCI6Ii8yMDQ1MTAwNC8zMDEwMDQzNjgtZjRkOWUwNTQtOTQ3Yi00ZDEwLTgxNzMtYjFjMDg0OGEyMGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDAwMzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZGMzMjZhZGJhMDk0ZGJiZGVkOTJmNWI0NWI1MGI5Y2E5Y2E2ODk0YjQ0NTIyYzIyMmE2ZWI0NGI5ODlmODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hJneHXcKuCcxr8455o5M1cI3E40ibmAn4cXaKBKE1c8) ![image](https://private-user-images.githubusercontent.com/20451004/301004603-0ea70ab9-0f97-4744-9e64-ec77553ebda6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MzU4ODAsIm5iZiI6MTcxMDYzNTU4MCwicGF0aCI6Ii8yMDQ1MTAwNC8zMDEwMDQ2MDMtMGVhNzBhYjktMGY5Ny00NzQ0LTllNjQtZWM3NzU1M2ViZGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDAwMzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMmFjNmU1ZTAxNjFiODcwN2I0MDgwN2I4ODE5YWM4Yjk2MWVmMDRmMDVjZjQxNTBlYmZhNzg0Mzg2Yzc3OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rc5j1-ObzZ2xMRvCQTlAMHviS9cvBsLIndXKNoL9ls0) 直接运行没问题 ![image](https://private-user-images.githubusercontent.com/20451004/301004948-998ea125-c5bd-45ad-ac5e-5ce823d501da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MzU4ODAsIm5iZiI6MTcxMDYzNTU4MCwicGF0aCI6Ii8yMDQ1MTAwNC8zMDEwMDQ5NDgtOTk4ZWExMjUtYzViZC00NWFkLWFjNWUtNWNlODIzZDUwMWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDAwMzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMDllMGE0NmNjZWE2NWMwODlmMWI4ZmYxZmI2MGNkMWU5MzEwY2M2MWRhODliNzYyYzg4NDMwMGRiZGJmZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NWRbMHtJEGZgxc_7HoXy2QKdob_RvFoCwx9ajc_6flo) 运行可执行文件出错 ![image](https://private-user-images.githubusercontent.com/20451004/301005096-6a55f06e-4f1c-4f4e-9c77-1f5400cb05b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MzU4ODAsIm5iZiI6MTcxMDYzNTU4MCwicGF0aCI6Ii8yMDQ1MTAwNC8zMDEwMDUwOTYtNmE1NWYwNmUtNGYxYy00ZjRlLTljNzctMWY1NDAwY2IwNWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDAwMzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NWMwMWM3NTNmOTBhMzFmMGRjZTY0M2I4M2ExMmVjNTlkNTljYzM3YmU4MjkxMmM3NDc4MDc1MzMxODRhMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IUFtBsNOMMT-1JqhYWT8zkSODwYQS1qVtI9sJdkzz-o)

用python -m pyinstaller试试
