### ISSUE TITLE
爬过的ID列表再次爬的时候会报错

### ISSUE THREAD

**Issue by Crazy-FuQing** [NanmiCoder/MediaCrawler#123]
开发大大你好，在爬取新增评论的时候出现这种错误，请问该咋样解决呢
![image](https://github.com/NanmiCoder/MediaCrawler/assets/46838021/0a44638a-2e70-41f1-b001-caf643c73f98)

**Comment by MrBeike** [comment]
> 开发大大你好，在爬取新增评论的时候出现这种错误，请问该咋样解决呢 ![image](https://private-user-images.githubusercontent.com/46838021/299012797-0a44638a-2e70-41f1-b001-caf643c73f98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMzc0NTMsIm5iZiI6MTcwNjIzNzE1MywicGF0aCI6Ii80NjgzODAyMS8yOTkwMTI3OTctMGE0NDYzOGEtMmU3MC00MWYxLWIwMDEtY2FmNjQzYzczZjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDAyNDU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNDdmM2Y3MjAzZGVkZTUwMDgxYTZlYjFmNzdmNmNjNWQzNGY5ODA3ZGRhYmIyOTA3YmU5NWQ1MThkYjFhYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SLe_SKMrLTPi_ZueHEE6VrBU3k1zgRrlEdOqrsy_Kgs)

同样的问题，保存方式换成db后，第一次开爬过程中遇到了此类情况，前面爬取的80多条数据库内正常。换成json保存一切正常。

**Comment by NanmiCoder** [comment]
已修复该问题，拉去最新代码～
