### ISSUE TITLE
2024-01-25  15:18:14 MediaCrawler INFO [XHSLogin.check_login_state] 登录过程中出现验证码，请手动验证

### ISSUE THREAD

**Issue by hele2069** [NanmiCoder/MediaCrawler#125]
扫描完登录qr code以后，提示以上的信息，但是我xhs客户端并没有受到验证码是什么问题呀

**Comment by NanmiCoder** [comment]
这个是指打开的浏览器驱动出现了验证码，把下面的配置改为False，你跑程序的时候会启动一个浏览器，然后就能看见小红书登录成功后还要验证滑块了。
https://github.com/NanmiCoder/MediaCrawler/blob/f1d3bc6e28fe3e373347d0114dcfb5579fce9ded/config/base_config.py#L14-L15
