### ISSUE TITLE
抖音用cookie登陆search报错，clone下来的项目没改过，有大佬帮忙看下吗？

### ISSUE THREAD

**Issue by hopemeng** [NanmiCoder/MediaCrawler#127]
python3 main.py --platform dy --lt cookie --type search
cookie是网页版里拿的
<img width="989" alt="image" src="https://github.com/NanmiCoder/MediaCrawler/assets/20451004/5a95372b-6362-4f80-948c-8ce286d134bc">

**Comment by NanmiCoder** [comment]
看下项目里的常见错误说明
