### ISSUE TITLE
关于redis

### ISSUE THREAD

**Issue by ljaupup** [NanmiCoder/MediaCrawler#13]
大佬，请问一下，抖音评论爬取是不是还不可以通过redis存储到数据库中？
能麻烦加一个windows 的 redis配置过程吗。
please😜

**Comment by NanmiCoder** [comment]
关于数据持久化部分目前计划的是存到 csv 或 excel ，入数据库的话可以先自行实现～

**Comment by ljaupup** [comment]
> 
好的好的🖐️[击掌]

**Comment by yundabei** [comment]
请问数据持久化部分可以做成根据热度排行/最新数据   然后有个时间节点 比如 2023/6/1-2023/7/12 ,这种类型的吗

**Comment by NanmiCoder** [comment]
> 请问数据持久化部分可以做成根据热度排行/最新数据 然后有个时间节点 比如 2023/6/1-2023/7/12 ,这种类型的吗

目前本职工作比较忙，可能会延后一段时间，如果可以的话，欢迎你针对你这部分提交PR

**Comment by NanmiCoder** [comment]
最新的commit e75707443b8f0ecfeddab7a9624983a4f6c5cb71 已经支持将抓取的数据保存到数据库中了（关系型数据库），查看README配置即可。
