### ISSUE TITLE
在没有界面的linux里面是否没有办法使用小红书登陆，因为无法出现登陆界面。。。

### ISSUE THREAD

**Issue by oscgking** [NanmiCoder/MediaCrawler#130]
例如使用了ubuntu的服务器版本？

谢谢大神

**Comment by NanmiCoder** [comment]
扫码登录不支持linux系统，可以更换为cookie模式。

**Comment by chen-junl** [comment]
> 扫码登录不支持linux系统，可以更换为cookie模式。

cookie设置的是哪个值

![Image](https://github.com/user-attachments/assets/df446b4c-1cbb-4f51-8687-318c2fea24dc)

**Comment by hztBUAA** [comment]
@chen-junl bro, 你解决了吗？ 是采用哪个字段？

**Comment by hztBUAA** [comment]
<img width="2225" height="1081" alt="Image" src="https://github.com/user-attachments/assets/3c31dafb-ddd3-4f86-9e92-6ef65f07d589" />
solved
