### ISSUE TITLE
运行为什么没有反应呢

### ISSUE THREAD

**Issue by haorongchen1015** [NanmiCoder/MediaCrawler#131]
在安装完库和playwright后，在conda 使用python3 main.py --platform xhs --lt qrcode --type search他没报错也没有弹出其他窗口或者显示运行进度，这是为什么呢。。

**Comment by NanmiCoder** [comment]
请问现在是否启动起来了？

**Comment by pugt99** [comment]
> 请问现在是否启动起来了？

  您好！我目前也遇到这个问题 没有反应是因为哪里操作不对吗？

**Comment by NanmiCoder** [comment]
> > 请问现在是否启动起来了？
> 
> 您好！我目前也遇到这个问题 没有反应是因为哪里操作不对吗？

可以贴一下你的运行方式吗，越详细越好，我这边排查一下原因，另外这个周末我出一个视频的入门教程，到时候关注一下。

**Comment by pugt99** [comment]
> > > 请问现在是否启动起来了？
> > 
> > 
> > 您好！我目前也遇到这个问题 没有反应是因为哪里操作不对吗？
> 
> 可以贴一下你的运行方式吗，越详细越好，我这边排查一下原因，另外这个周末我出一个视频的入门教程，到时候关注一下。

我已经解决了这问题  运行代码修改为：python main.py --platform xhs --lt qrcode --type search
