### ISSUE TITLE
[请教] 关于xhs爬取notes时只会获取到其中的一小部分

### ISSUE THREAD

**Issue by AllenZHU23** [NanmiCoder/MediaCrawler#139]
Hi, 想请教一下，在使用关键词对xhs的帖子进行爬取时 (基于这个/api/sns/web/v1/search/notes)，我发现只能获取到其中一部分的帖子。
比如，指定keyword = “人工智能“，通过这个api只能获取到200条左右的note (程序运行正常)，但实际上xhs中关于"人工智能”的帖子数量应该远远不止这么多......
想请教一下，是因为这个api在获取notes的时候本身就有数量限制嘛？如果想获取到全部的notes，有没有什么比较好的解决方案呢？谢谢~

**Comment by NanmiCoder** [comment]
肯定有限制的，要是一个账号就把小红书的所有笔记获取了，那小红书的安全团队就形同摆设了。可以去了解这些大公司做的风控就清楚你现在的需求几乎没啥好的解决方案。

Allen ***@***.***>于2024年2月25日 周日23:19写道：

**Comment by lzy350593418** [comment]
> Hi, 想请教一下，在使用关键词对xhs的帖子进行爬取时 (基于这个/api/sns/web/v1/search/notes)，我发现只能获取到其中一部分的帖子。 比如，指定keyword = “人工智能“，通过这个api只能获取到200条左右的note (程序运行正常)，但实际上xhs中关于"人工智能”的帖子数量应该远远不止这么多...... 想请教一下，是因为这个api在获取notes的时候本身就有数量限制嘛？如果想获取到全部的notes，有没有什么比较好的解决方案呢？谢谢~

请教下，你是怎么获取的呢？需要传什么参数呢。。/api/sns/web/v1/search/notes我一直访问code=-1,没访问成功

**Comment by AllenZHU23** [comment]
后来我发现这个api只能获取到一部分的note_id（肯定不全），所以后来没用这个接口来拿了😂

**Comment by xeoshow** [comment]
> 后来我发现这个api只能获取到一部分的note_id（肯定不全），所以后来没用这个接口来拿了😂
> […](#)

那你现在怎么解决搜索的呢？谢谢
