### ISSUE TITLE
小红书 登录后，重启程序需要重新再登录吗？没有保存登录信息。

### ISSUE THREAD

**Issue by xuminzhong** [NanmiCoder/MediaCrawler#14]
如题

**Comment by NanmiCoder** [comment]
hello，是需要重新登录的，目前这块功能优先级暂时比较靠后，可以先自行实现，欢迎提交PR~

**Comment by xuminzhong** [comment]
谢谢，我改用 launch_persistent_context 可以保存登录信息了，
然后在 XHSLogin.begin 前，判断当前是否已登录就行了。

另一个可能是Bug，在 recv_sms_notification.py 里 config.redis_db_host 和 config.redis_db_pwd 应该是大写的 REDIS_DB_HOST。

**Comment by NanmiCoder** [comment]
recv_sms_notification.py redis的配置文件大小写忘记改了，确实是个bug，后续commit中会修复一下，谢谢提醒~

**Comment by NanmiCoder** [comment]
hello，最新的commit dad8d56ab5a282f5560e12a36286eebfc6cb0082  已经修复了这两个问题了。使用者可以在配置文件中选择是否开启缓存登录 https://github.com/NanmiCoder/MediaCrawler/blob/dad8d56ab5a282f5560e12a36286eebfc6cb0082/config/base_config.py#L21

在浏览器启动的时候，会创建指定的BrowserContext
https://github.com/NanmiCoder/MediaCrawler/blob/dad8d56ab5a282f5560e12a36286eebfc6cb0082/media_platform/xhs/core.py#L146-L165
