### ISSUE TITLE
能不能来个详细的配置教程啊，小白表示很难入手

### ISSUE THREAD

**Issue by Liyff** [NanmiCoder/MediaCrawler#143]

**Comment by NanmiCoder** [comment]
这个问题已经发现了，周末考虑出一个视频教程。

**Comment by NanmiCoder** [comment]
- [ ] 周末录制MediaCrawler小白入门视频

**Comment by dpc137** [comment]
> 这个问题已经发现了，周末考虑出一个视频教程。

大佬准备视频发到哪里哇

**Comment by NanmiCoder** [comment]
> > 这个问题已经发现了，周末考虑出一个视频教程。
> 
> 大佬准备视频发到哪里哇

已经将视频发到B站了，链接地址在主页有。

**Comment by aswind7** [comment]
> > > 这个问题已经发现了，周末考虑出一个视频教程。
> > 
> > 
> > 大佬准备视频发到哪里哇
> 
> 已经将视频发到B站了，链接地址在主页有。

太强了 
![FC4E7C7D](https://github.com/NanmiCoder/MediaCrawler/assets/12571054/dc95dc50-fd8b-4f30-a838-3b6be654ebad)
