### ISSUE TITLE
小红书评论如何能获取到评论的图片呀？

### ISSUE THREAD

**Issue by semsevens** [NanmiCoder/MediaCrawler#145]
小红书评论如何能获取到评论的图片呀？

**Comment by NanmiCoder** [comment]
请提供一个能获取到评论图片的笔记链接示例

**Comment by semsevens** [comment]
> 请提供一个能获取到评论图片的笔记链接示例

https://www.xiaohongshu.com/explore/65535d02000000000f02b445

**Comment by NanmiCoder** [comment]
已经支持 commit见：https://github.com/NanmiCoder/MediaCrawler/commit/41fee4ff4f9fed4c604d8e92eecc43182dcad715

**Comment by souldjl** [comment]
> 已经支持 commit见：[41fee4f](https://github.com/NanmiCoder/MediaCrawler/commit/41fee4ff4f9fed4c604d8e92eecc43182dcad715)

好像获取到的 链接无法直接访问呢 ？ 
  "pictures": [
            {
                "height": 1080,
                "width": 1080,
                "url_pre": "http://sns-webpic-qc.xhscdn.com/202506100002/a669f25f1bb6455775d3d2b34a2b125b/comment/1040g2h031gk1rgvhji6g434mkqtc47l7hrv4800!nc_n_webp_mw_1",
                "url_default": "http://sns-webpic-qc.xhscdn.com/202506100002/5aa2d13fa5254aa5a1298b510444eb52/comment/1040g2h031gk1rgvhji6g434mkqtc47l7hrv4800!nd_whgt34_webp_wm_1",
                "info_list": [
                    {
                        "image_scene": "WB_PRV",
                        "url": "http://sns-webpic-qc.xhscdn.com/202506100002/a669f25f1bb6455775d3d2b34a2b125b/comment/1040g2h031gk1rgvhji6g434mkqtc47l7hrv4800!nc_n_webp_mw_1"
                    },
                    {
                        "image_scene": "WB_DFT",
                        "url": "http://sns-webpic-qc.xhscdn.com/202506100002/5aa2d13fa5254aa5a1298b510444eb52/comment/1040g2h031gk1rgvhji6g434mkqtc47l7hrv4800!nd_whgt34_webp_wm_1"
                    }
                ]
            }
        ],
