### ISSUE TITLE
微博评论数据爬取失败

### ISSUE THREAD

**Issue by ly1327** [NanmiCoder/MediaCrawler#146]
评论数据爬取失败，是什么问题呢？以下是日志输出内容：
MediaCrawler ERROR [WeiboCrawler.get_note_comments] may be been blocked, err:Expecting value: line 1 column

**Comment by NanmiCoder** [comment]
微博平台的话可能IP被暂时封禁了，过一会尝试一下还报错吗

**Comment by ly1327** [comment]
一直都没成功过，我这几天尝试很多遍了

**Comment by ly1327** [comment]
@NanmiCoder
