### ISSUE TITLE
抖音评论爬取失败

### ISSUE THREAD

**Issue by shimada-hanzo** [NanmiCoder/MediaCrawler#147]
报错内容
> 2024-03-09  02:42:55 MediaCrawler ERROR [DouYinCrawler.get_comments] aweme_id: 7217647166863461691 get comments failed, error: Expecting value: line 1 column 1 (char 0),

上网查询后我发现Expecting value: line 1 column 1 (char 0),多见于返回的数据不是完整的json数据格式，我定位到了media_platform/douyin/client.py里的get_aweme_comments()函数。
输出referer_url并手动访问发现是404页面，进一步分析后发现keywords变量为空，并且对它的三个引用中似乎没有赋值的部分？求解答报错原因，以及referer_url里硬编码的aid=xxxxx有什么作用？

**Comment by NanmiCoder** [comment]
这种一般是账号被封了 过一会儿再试试

**Comment by shimada-hanzo** [comment]
我擦，原来是这样，我晚上再试一下。
