### ISSUE TITLE
抖音二维码登录问题！

### ISSUE THREAD

**Issue by xtuyaowu** [NanmiCoder/MediaCrawler#15]
你好：
      试了一下抖音二维码登录，也是需要短信验证？

**Comment by NanmiCoder** [comment]
hello, 从我自己的账号测试来看，扫码登录没有触发过短信验证码，过程中可能会触发滑块验证，但是也是不可控的。

**Comment by xtuyaowu** [comment]
我给你发了邮件，请查收，谢谢！

**Comment by NanmiCoder** [comment]
如果你的抖音账号在扫码登录过程中会触发短信验证的话，建议换个账号使用或者使用 cookies 的方式，这边仓库没办法去兼容这种情况，往理解～

**Comment by xtuyaowu** [comment]
好的，谢谢，可否加个好友，或者建个群 交流一下！

**Comment by NanmiCoder** [comment]
涉及爬虫或逆向类的不打算建群，毕竟可能无意间就会触发某些xxx，有什么问题可在issue中提出来就行，有空了我会回复的😁

**Comment by xtuyaowu** [comment]
加个好友吧，email 你了！

**Comment by xtuyaowu** [comment]
关闭
