### ISSUE TITLE
大佬，小红书这个日期和图片应该怎么显示呢？改动哪里

### ISSUE THREAD

**Issue by ifredom** [NanmiCoder/MediaCrawler#153]
![image](https://github.com/NanmiCoder/MediaCrawler/assets/13759936/88b8609d-d98a-4090-9670-439dbd99f10a)

**Comment by NanmiCoder** [comment]
日期的话调整单元格格式为文本试试，图片的话看下这个文件MediaCrawler/media_platform/xhs/help.py ，可以下载https://github.com/NanmiCoder/MediaCrawler/blob/b48e4d297dc82d930006fc5ad7366121f9535c33/media_platform/xhs/help.py#L279-L284

**Comment by ifredom** [comment]
> 日期的话调整单元格格式为文本试试，图片的话看下这个文件MediaCrawler/media_platform/xhs/help.py ，可以下载
> 
> https://github.com/NanmiCoder/MediaCrawler/blob/b48e4d297dc82d930006fc5ad7366121f9535c33/media_platform/xhs/help.py#L279-L284

python我是个初学者，意思是我可以直接在目录[media_platform/xhs 下执行 python help.py 对吗？这样岂不是只能一个一个的下载

**Comment by NanmiCoder** [comment]
> > 日期的话调整单元格格式为文本试试，图片的话看下这个文件MediaCrawler/media_platform/xhs/help.py ，可以下载
> > https://github.com/NanmiCoder/MediaCrawler/blob/b48e4d297dc82d930006fc5ad7366121f9535c33/media_platform/xhs/help.py#L279-L284
> 
> python我是个初学者，意思是我可以直接在目录[media_platform/xhs 下执行 python help.py 对吗？这样岂不是只能一个一个的下载

这里只是提供了一个下载图片的方法，对你已经爬取的数据进行一个for循环遍历，然后使用这个下载图片的方法就可以了，中间加一些自己的逻辑，实在不行，可以把你的需求和代码片段告诉GPT，它应该能很快帮你生产。

**Comment by ifredom** [comment]
> > > 日期的话调整单元格格式为文本试试，图片的话看下这个文件MediaCrawler/media_platform/xhs/help.py ，可以下载
> > > https://github.com/NanmiCoder/MediaCrawler/blob/b48e4d297dc82d930006fc5ad7366121f9535c33/media_platform/xhs/help.py#L279-L284
> > 
> > 
> > python我是个初学者，意思是我可以直接在目录[media_platform/xhs 下执行 python help.py 对吗？这样岂不是只能一个一个的下载
> 
> 这里只是提供了一个下载图片的方法，对你已经爬取的数据进行一个for循环遍历，然后使用这个下载图片的方法就可以了，中间加一些自己的逻辑，实在不行，可以把你的需求和代码片段告诉GPT，它应该能很快帮你生产。

好的，感谢大佬，我研究研究，看看怎么搞

**Comment by ifredom** [comment]
> > > 日期的话调整单元格格式为文本试试，图片的话看下这个文件MediaCrawler/media_platform/xhs/help.py ，可以下载
> > > https://github.com/NanmiCoder/MediaCrawler/blob/b48e4d297dc82d930006fc5ad7366121f9535c33/media_platform/xhs/help.py#L279-L284
> > 
> > 
> > python我是个初学者，意思是我可以直接在目录[media_platform/xhs 下执行 python help.py 对吗？这样岂不是只能一个一个的下载
> 
> 这里只是提供了一个下载图片的方法，对你已经爬取的数据进行一个for循环遍历，然后使用这个下载图片的方法就可以了，中间加一些自己的逻辑，实在不行，可以把你的需求和代码片段告诉GPT，它应该能很快帮你生产。

好的，感谢大佬，我研究研究，看看怎么搞

**Comment by Lalatu03** [comment]
您好，我也是用csv下载的小红书的评论，日期这里我调成文本也不管用，都显示的是，求佬帮看看应该怎么办呀？我也是小白不太会python……

![Image](https://github.com/user-attachments/assets/2d189a23-36cb-408d-9c3d-4fc22a477dae)
