### ISSUE TITLE
小红书主页 爬取用户笔记超过几十条后出现错误

### ISSUE THREAD

**Issue by insomniai** [NanmiCoder/MediaCrawler#154]
MediaCrawler ERROR [XiaoHongShuCrawler.get_note_detail] Get note detail error: required param: source_note_id not found

好像需要额外的参数了

**Comment by ifredom** [comment]
同样的问题， 评论太多了，抓的很慢，不想要comment应该怎么改一下启动指令。
![image](https://github.com/NanmiCoder/MediaCrawler/assets/13759936/7c6ff582-34ba-4ae1-a12c-33b456837e9f)

**Comment by ifredom** [comment]
xhs 这里的分页有BUG，等作者更新吧~

**Comment by NanmiCoder** [comment]
已经修复，请拉取最新代码尝试。
