### ISSUE TITLE
小红书主页 type=creator时，如何只抓取content

### ISSUE THREAD

**Issue by ifredom** [NanmiCoder/MediaCrawler#155]
如题，当小红书type为创作者时，默认会抓取3个内容。

1. BUG: 主页内容只能抓取到30条，从第30条开始都重复了。默认分页是30，我尝试改了一下60，无效。只能30条？
2. help : 评论 comments太多了，导致一个人的主页会抓取20多分钟......不要评论，启动参数应该怎么样设置跳过comments呢？

![image](https://github.com/NanmiCoder/MediaCrawler/assets/13759936/4e64148b-e78e-4776-8961-9eb02e0ab518)

![image](https://github.com/NanmiCoder/MediaCrawler/assets/13759936/d728ef78-cfba-46ea-8f77-2b67d8c6abd3)

启动参数,修改config这2个值后启动：`  python main.py`

![image](https://github.com/NanmiCoder/MediaCrawler/assets/13759936/4403dc37-efe0-4b6d-9dc4-3ca99f9919ee)

**Comment by NanmiCoder** [comment]
这个模式有bug，这周末修复

**Comment by ifredom** [comment]
看到新增跳过了comments配置。运行  `python main,py`出现新bug,

使用 CRAWLER_TYPE = "creator"  获取创作者 62b450a30000000015016cc5 的主页内容

配置文件改动如下：
```

CRAWLER_TYPE = "creator"

# 指定小红书创作者ID列表
XHS_CREATOR_ID_LIST = [
    "62b450a30000000015016cc5",
    # ........................
]

```
![image](https://github.com/NanmiCoder/MediaCrawler/assets/13759936/de92e033-f5fe-4c7a-b7c0-6a3e8b4b06c5)

**Comment by NanmiCoder** [comment]
已修复该问题

**Comment by gauge6745** [comment]
借楼问，有没有只爬主页数据的方法，不需要content的数据
