### ISSUE TITLE
【Bug】playwright issue, how to resolve it

### ISSUE THREAD

**Issue by vvip2u** [NanmiCoder/MediaCrawler#158]
日志：

```
playwright._impl._api_types.Error: Host system is missing dependencies!

Full list of missing libraries:
    chrome_elf.dll
```

**Comment by NanmiCoder** [comment]
什么环境下运行的？

**Comment by polikhronidi** [comment]
> playwright._impl._api_types.Error: Host system is missing dependencies!
> 
> Full list of missing libraries:
>     chrome_elf.dll

If you encounter the error `playwright._impl._api_types.Error: Host system is missing dependencies!`, it signifies that the necessary libraries for Playwright to function properly are absent on your system.

#### Try next:

1. **Review Playwright Documentation**: Start by consulting the Playwright documentation to ensure you have correctly installed all the prerequisites for your specific operating system.

2. **Install Missing Libraries**: Search for the missing `chrome_elf.dll` library online and install it according to your operating system's requirements. Alternatively, consider reinstalling Playwright or its dependencies to ensure all essential libraries are included.

3. **Update Playwright**: Ensure that you are using the latest version of Playwright, as newer releases often contain fixes or enhancements that address dependency-related issues.

4. **Check Operating System Compatibility**: Verify that your operating system is compatible with Playwright. Certain libraries may be tailored to specific operating systems, so confirm that you are using Playwright on a supported platform.

5. **Environment Setup**: Double-check your environment setup to rule out any potential conflicts or issues with other installed software that might interfere with Playwright's functionality.

**Comment by vvip2u** [comment]
Windows 11

按照ReadMe中【使用方法】操作的
