### ISSUE TITLE
小红书运行后报错

### ISSUE THREAD

**Issue by LeyiJiang** [NanmiCoder/MediaCrawler#159]
你好，我想问一下，扫码了确认登录了但是报这些错是为什么呀！
![报错代码](https://github.com/NanmiCoder/MediaCrawler/assets/102365757/8af756c7-2a08-44b0-a5c2-61fb40149c45)

**Comment by NanmiCoder** [comment]
是开的有全局VPN代理吗？

**Comment by LeyiJiang** [comment]
已收到作业，祝学业进步，万事胜意。

**Comment by LeyiJiang** [comment]
是的是的，谢谢！！！

**Comment by LeyiJiang** [comment]
大佬我又来了，是因为我爬取太多条了吗，会显示
2024-03-18  15:07:21 MediaCrawler INFO [XiaoHongShuCrawler.search] Note details: [] 
2024-03-18  15:07:21 MediaCrawler INFO [XiaoHongShuCrawler.batch_get_note_comments] Crawling comment mode is not enabled 
如下图所示
![a4639522cd064f6ef6e28816483adbc6](https://github.com/NanmiCoder/MediaCrawler/assets/102365757/f8502f4e-8ca0-46dc-b4ad-0cf02efcb708)

**Comment by NanmiCoder** [comment]
账号可能被ban了

**Comment by kevinzxz** [comment]
我也出现这个情况并且只能爬取200出头的条数似乎
