### ISSUE TITLE
小红书扫码后提示登录过程中出现验证码，请手动验证

### ISSUE THREAD

**Issue by ivone-liu** [NanmiCoder/MediaCrawler#162]
![Uploading PixPin_2024-03-18_13-14-25.png…](https://github.com/ivone-liu/picx-images-hosting/raw/master/20240318/PixPin_2024-03-18_13-14-25.58h4jhlp1o.webp)

**Comment by LeyiJiang** [comment]
博主的视频里面有说，手动验证的话就把base_config.py文件里面的，HEADLESS改成false就行了
