### ISSUE TITLE
数据输出卡住

### ISSUE THREAD

**Issue by yundabei** [NanmiCoder/MediaCrawler#17]
运行之后发现只能输出大概200+的数据,然后就不在输出了,主题和评论加起来200+,这是小红书限制了还是其他什么原因呢

**Comment by NanmiCoder** [comment]
看下这个issue，https://github.com/NanmiCoder/MediaCrawler/issues/6，如果跟他遇到情况不一样的话， 把你的运行参数等信息给我，我这边来复现一下

**Comment by NanmiCoder** [comment]
hello，你可以拉下最新的代码看下是否还有这个问题，原来的逻辑如果抓取完成了程序中会一直阻塞，所以在使用者看起来就像数据一直卡着一样，新的commit中已经优化这部分了

**Comment by NanmiCoder** [comment]
目前已修复该问题，请持续观察，如果还有此类问题，重新打开该issue，我再看一下。
