### ISSUE TITLE
账号没有访问权限，如何解决？新建虚拟环境也不行

### ISSUE THREAD

**Issue by IchvanHuang** [NanmiCoder/MediaCrawler#175]
<img width="563" alt="image" src="https://github.com/NanmiCoder/MediaCrawler/assets/106398365/9db04b38-2f26-4392-a76d-44e76421ea33">

**Comment by IchvanHuang** [comment]
不再弹出二维码窗口

**Comment by wangjianpeng** [comment]
最后怎么解决呢？

**Comment by NanmiCoder** [comment]
可能有滑块验证码，需要手动过一样

penney ***@***.***>于2024年4月2日 周二20:50写道：
