### ISSUE TITLE
提个醒

### ISSUE THREAD

**Issue by Jazzylol** [NanmiCoder/MediaCrawler#185]
作者开源的，后续有人用这个仓库的技术被报警，如果被指认，作者也要跟着进去。。、

免责并不一定有用...

https://github.com/HiddenStrawberry/Crawler_Illegal_Cases_In_China?tab=readme-ov-file

![image](https://github.com/NanmiCoder/MediaCrawler/assets/8966893/3bde835d-e805-453d-88c1-75230d8eb597)

**Comment by NanmiCoder** [comment]
thanks：
