### ISSUE TITLE
请问，在哪里配置抖音的搜索关键词

### ISSUE THREAD

**Issue by wuxiaol1981** [NanmiCoder/MediaCrawler#186]
不知道在哪配置关键词
运行出错
![2](https://github.com/NanmiCoder/MediaCrawler/assets/62429849/d5c66ae8-8b54-4c4e-abf8-b7b8098e43c8)
![1](https://github.com/NanmiCoder/MediaCrawler/assets/62429849/d1e3a578-bd82-447a-a93b-08d8d165c3a4)

**Comment by NanmiCoder** [comment]
看下常见问题
