### ISSUE TITLE
二维码登录

### ISSUE THREAD

**Issue by huangqueji** [NanmiCoder/MediaCrawler#19]
二维码登录不可用，需要滑块验证了
`<Page url='https://www.xiaohongshu.com/website-login/captcha?redirectPath=> `

**Comment by NanmiCoder** [comment]
我也发现了，目前小红书的旋转滑块过不了，建议在配置文件中开启保存上一次登录信息的选项，然后首次启动项目时，手动滑动成功一次后，后续跑项目就不会出现滑块验证了，如果后面有新的方案，我会在该issue回复你。

**Comment by NanmiCoder** [comment]
这个问题目前已经解决了，在浏览器打开小红书页面之前，添加一个webId的Cookie就不会出现验证码，你试试。
https://github.com/NanmiCoder/MediaCrawler/blob/03565d61c6e2ac653ec3e0a10b15e85e9edc0f4f/media_platform/xhs/core.py#L49-L57

**Comment by huangqueji** [comment]
谢谢dl

**Comment by terryleetracymc** [comment]
> 这个问题目前已经解决了，在浏览器打开小红书页面之前，添加一个webId的Cookie就不会出现验证码，你试试。
> 
> https://github.com/NanmiCoder/MediaCrawler/blob/03565d61c6e2ac653ec3e0a10b15e85e9edc0f4f/media_platform/xhs/core.py#L49-L57

请教下，这个是基于什么原理
