### ISSUE TITLE
请问cookie在哪里填写，填写的格式是怎样的？

### ISSUE THREAD

**Issue by Looper0331** [NanmiCoder/MediaCrawler#194]
请问cookie在哪里填写，填写的格式是怎样的？

![image](https://github.com/NanmiCoder/MediaCrawler/assets/66026703/26332481-401e-49da-ab82-c9b8d2fe0d34)

config中没有具体说明

**Comment by txl16095** [comment]
> 请问cookie在哪里填写，填写的格式是怎样的？
> 
> ![image](https://private-user-images.githubusercontent.com/66026703/316406320-26332481-401e-49da-ab82-c9b8d2fe0d34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MjMzNjEsIm5iZiI6MTcxMjYyMzA2MSwicGF0aCI6Ii82NjAyNjcwMy8zMTY0MDYzMjAtMjYzMzI0ODEtNDAxZS00OWRhLWFiODItYzliOGQyZmUwZDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDAwMzc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MTQ4YTlhOTcyODc4NGIyM2I5NzNiOTc3OTY2ZDFiYThlZWYyMDc4YzNiNDIwNmFiNWIwMGIzNmEzZjFlZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pahsxfX9U7-ydNO_CI0aok---vTxzL8RDepu79X2uyc)
> 
> config中没有具体说明

以某音为例，你直接去请求某音的接口，F12后在请求头里把cookie的值全部复制下来，然后填入这个配置中的cookie即可。
