### ISSUE TITLE
小红书水印该如何去掉

### ISSUE THREAD

**Issue by HanchuQin** [NanmiCoder/MediaCrawler#196]
作者大大，现在api直接返回的image_list是带水印的链接，这几天百度了下以前是靠替换traceID来获得无水印的链接，现在没有返回traceID了，应该怎么获得无水印的图片的URL呢？

**Comment by DongTin** [comment]
+1

**Comment by leosongyyy** [comment]
我看网页版 traceID 好像默认不给了

**Comment by DongTin** [comment]
可以在网页源码里找到http://sns-webpic-qc.xhscdn.com/202404121854/a7e6fa93538d17fa5da39ed6195557d7/0302bl013q38is9i74j011an5512g627ek!nd_dft_wlteh_webp_3 其中0302bl013q38is9i74j011an5512g627ek为图片标识符 将链接替换为https://ci.xiaohongshu.com/0302b1013g38is9i74j011an5512g627ek?imageView2/2/w/0/format/jpg/v3 得到无水印图片

| |
刘昱琨
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 04/15/2024 01:38 |
| To | NanmiCoder/MediaCrawler ***@***.***> |
| Cc | DongTin ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [NanmiCoder/MediaCrawler] 小红书水印该如何去掉 (Issue #196) |

我看网页版 traceID 好像默认不给了

**Comment by HanchuQin** [comment]
> 可以在网页源码里找到http://sns-webpic-qc.xhscdn.com/202404121854/a7e6fa93538d17fa5da39ed6195557d7/0302bl013q38is9i74j011an5512g627ek!nd_dft_wlteh_webp_3 其中0302bl013q38is9i74j011an5512g627ek为图片标识符 将链接替换为https://ci.xiaohongshu.com/0302b1013g38is9i74j011an5512g627ek?imageView2/2/w/0/format/jpg/v3 得到无水印图片 | | 刘昱琨 | | ***@***.*** | ---- Replied Message ---- | From | ***@***.***> | | Date | 04/15/2024 01:38 | | To | NanmiCoder/MediaCrawler ***@***.***> | | Cc | DongTin ***@***.***>, Comment ***@***.***> | | Subject | Re: [NanmiCoder/MediaCrawler] 小红书水印该如何去掉 (Issue #196) | 我看网页版 traceID 好像默认不给了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

大佬能不能把方法代码给一个

**Comment by yuvenhol** [comment]
> 可以在网页源码里找到http://sns-webpic-qc.xhscdn.com/202404121854/a7e6fa93538d17fa5da39ed6195557d7/0302bl013q38is9i74j011an5512g627ek!nd_dft_wlteh_webp_3 其中0302bl013q38is9i74j011an5512g627ek为图片标识符 将链接替换为https://ci.xiaohongshu.com/0302b1013g38is9i74j011an5512g627ek?imageView2/2/w/0/format/jpg/v3 得到无水印图片 | | 刘昱琨 | | ***@***.*** | ---- Replied Message ---- | From | ***@***.***> | | Date | 04/15/2024 01:38 | | To | NanmiCoder/MediaCrawler ***@***.***> | | Cc | DongTin ***@***.***>, Comment ***@***.***> | | Subject | Re: [NanmiCoder/MediaCrawler] 小红书水印该如何去掉 (Issue #196) | 我看网页版 traceID 好像默认不给了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

已经不行了吧
