### ISSUE TITLE
XHS可以实现只抓取帖子信息不抓取评论吗？

### ISSUE THREAD

**Issue by dh372101** [NanmiCoder/MediaCrawler#200]
每个帖子的评论都抓取效率有些慢

**Comment by NanmiCoder** [comment]
请更新最新代码尝试，配置文件中有一个选项用于支持是否爬取评论。
https://github.com/NanmiCoder/MediaCrawler/blob/aa257aab5196f5d4f0054f2805cb180831b4b4b1/config/base_config.py#L33-L34
