### ISSUE TITLE
方法失效

### ISSUE THREAD

**Issue by James-Heller** [NanmiCoder/MediaCrawler#205]
pong方法和 search方法似乎已经失效了

**Comment by leantli** [comment]
有具体的不能使用的截图和配置文件配置截图吗? 我这边刚才测试 xhs 正常的

**Comment by ScarlettSun9** [comment]
我测试dy，search 方法关键词检索，出问题了。。

![image](https://github.com/NanmiCoder/MediaCrawler/assets/53145308/8e9d078d-f432-48ee-a052-51ea5da9560d)

**Comment by NanmiCoder** [comment]
> 我测试dy，search 方法关键词检索，出问题了。。
> 
> ![image](https://private-user-images.githubusercontent.com/53145308/319150736-8e9d078d-f432-48ee-a052-51ea5da9560d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTc5NDYsIm5iZiI6MTcxMjE1NzY0NiwicGF0aCI6Ii81MzE0NTMwOC8zMTkxNTA3MzYtOGU5ZDA3OGQtZjQzMi00OGVlLWEwNTItNTFlYTVkYTk1NjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDE1MjA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxYjI5NDEwZGRjYjBhYTM3ZDAwMmUxNDU3Yjg1MjIwNTY4MDVjZjhjODQ5NTE2NjkwNzQxZWZlMTZjNmExNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HfAiZxRScu5kWXi0mqM8anZGvFt6mdp5fEPQSXZMAEk)

你这个是之前的老代码，请更新最新的代码。

**Comment by ScarlettSun9** [comment]
谢谢！已更新，发现检索链接变了。
