### ISSUE TITLE
当搜索某些关键词并且写入mysql时报错，看起来像字段类型对不上导致的

### ISSUE THREAD

**Issue by ralph-wren** [NanmiCoder/MediaCrawler#207]
![image](https://github.com/NanmiCoder/MediaCrawler/assets/65018890/6fc1533d-1a19-4d0d-ba4a-835602b95a50)

**Comment by NanmiCoder** [comment]
看起来是像是标题为空导致的，数据库这一块马上会移除orm的依赖

**Comment by NanmiCoder** [comment]
已经移除orm的内容，请更新最新代码尝试
