### ISSUE TITLE
微博哔哩哔哩这些都没有二级评论，是弄不到吗

### ISSUE THREAD

**Issue by 202774025** [NanmiCoder/MediaCrawler#221]

**Comment by NanmiCoder** [comment]
能获取到，但是如果选择开启二级评论会导致一个帖子评论获取的时间过长，从而使得爬的数据有限

**Comment by nelzomal** [comment]
@NanmiCoder 
爬取时间过长 为什么会影响数据数量？ 二级评论是可配置开启的，所以我写了一个Pull request支持 #273

**Comment by NanmiCoder** [comment]
> @NanmiCoder 爬取时间过长 为什么会影响数据数量？ 二级评论是可配置开启的，所以我写了一个Pull request支持 #273

之前二级评论不是可配置的
