### ISSUE TITLE
为什么我下载的代码只能下载评论，不能下载视频？

### ISSUE THREAD

**Issue by alexliusyx** [NanmiCoder/MediaCrawler#227]
小红书中core.py代码search函数               
 utils.logger.info(f"[XiaoHongShuCrawler.search] Note details: {note_id_list}")
await self.batch_get_note_comments(note_id_list)
就结束了。

**Comment by NanmiCoder** [comment]
当前这个仓库是不支持下载视频的，视频的链接已经保存了，可以在其他github仓库去找下载器即可
