### ISSUE TITLE
如何把数据保存进mysql中

### ISSUE THREAD

**Issue by alanzed555** [NanmiCoder/MediaCrawler#241]
首先感谢楼主好代码。

我已经运行db.py，在mysql中建好了库，也有了表。

请问需要设置哪个地方，才能让数据保存进mysql中？

#下面的base_config处我也设置了。
# 数据保存类型选项配置,支持三种类型：csv、db、json
# SAVE_DATA_OPTION = "json"  # csv or db or json
SAVE_DATA_OPTION = "db"  # csv or db or json

运行完毕后，mysql中还是没有数据（目前只测试了xhs）。

**Comment by alanzed555** [comment]
> debug看下有没有走到这里来
> 
> https://github.com/NanmiCoder/MediaCrawler/blob/59c683a05763a41e6152bab0a6da4f6c7824032f/store/xhs/xhs_store_sql.py#L29-L40

打断点了，完全没有运行到这里。。。
是某个地方有个存入mysql的开关设置吗/

**Comment by alanzed555** [comment]
> debug看下有没有走到这里来
> 
> https://github.com/NanmiCoder/MediaCrawler/blob/59c683a05763a41e6152bab0a6da4f6c7824032f/store/xhs/xhs_store_sql.py#L29-L40

你好楼主。
经过测试，xhs_note表中有数据了。
但是xhs_note_comment表中没有任何数据。
这是什么原因呢？

**Comment by NanmiCoder** [comment]
在配置文件中开启了保存评论了吗？

**Comment by alanzed555** [comment]
> 在配置文件中开启了保存评论了吗？

就是这个问题！

**Comment by geek2024811** [comment]
你好，mysql配置库，怎么配置表
