### ISSUE TITLE
运行报错，请问下面是什么问题？

### ISSUE THREAD

**Issue by frankchen2804** [NanmiCoder/MediaCrawler#244]
execjs._exceptions.ProgramError: TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null

**Comment by frankchen2804** [comment]
![1713773620666](https://github.com/NanmiCoder/MediaCrawler/assets/46262445/3fb364ac-24e3-4671-90fe-a4ec68a448ff)

**Comment by frankchen2804** [comment]
界面出现了：抱歉，当前浏览器无法正常观看直播，建议下载客户端或更换浏览器

**Comment by NanmiCoder** [comment]
这个不用管，不影响数据抓取。
