### ISSUE TITLE
我首次启动后，弹出来登录二维码，我用小红书 APP 扫码后，登录了。但是提示要手动验证，APP 也没有看到验证的地方。我重启项目后，再次操作，发现登录验证二维码获取不到。

### ISSUE THREAD

**Issue by wufu-fire** [NanmiCoder/MediaCrawler#245]

**Comment by leantli** [comment]
把下面 HEADLESS 配置项设置为 False, 重启项目后就会弹出浏览器, 然后就可以手动过验证码了

https://github.com/NanmiCoder/MediaCrawler/blob/aa257aab5196f5d4f0054f2805cb180831b4b4b1/config/base_config.py#L15-L16
