### ISSUE TITLE
抖音使用cookie方式一直登录失败？

### ISSUE THREAD

**Issue by another1s** [NanmiCoder/MediaCrawler#247]
如题，在config里进行LOGIN_TYPE有修改成“cookie”，然后COOKIES字段也在web端登录了抖音后，选取了https://www.douyin.com/user/self 这个页面的sessionid，复制并输了进去。
但启动一直报login failed，请问这个是我哪一步误操作了呢？

**Comment by another1s** [comment]
已经解决了，原来是要把所有的cookie拼在一起

**Comment by Kukuair** [comment]
补充一个快捷提取方法供后来人参考：安装[cookies-editor](https://chromewebstore.google.com/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm)，进入对应的平台（xhs，douyin，weibo）, 点击cookies-editor ——> Export ——> Header String 粘贴至config中的Cookies字段中
