### ISSUE TITLE
如何自动下载小红书文章内的图呢？

### ISSUE THREAD

**Issue by greatcat19** [NanmiCoder/MediaCrawler#249]
`python main.py --platform xhs --lt qrcode --type detail` 和 `python main.py --platform xhs --lt qrcode --type creator` 都不会下载图片，只有 metadata

**Comment by NanmiCoder** [comment]
仓库没有集成图片下载哈，请参考https://github.com/NanmiCoder/MediaCrawler/blob/2d051cc670fa88400882843d3e7de862312c0a0c/media_platform/xhs/help.py#L280-L284

**Comment by greatcat19** [comment]
感谢！
