### ISSUE TITLE
求问，如何将查询的结果导出到csv文件呢，求大大解答

### ISSUE THREAD

**Issue by XiMing666** [NanmiCoder/MediaCrawler#256]
求问，如何将查询的结果导出到csv文件呢，求大大解答
![image](https://github.com/NanmiCoder/MediaCrawler/assets/142143715/f982a2dc-8e17-40f4-8674-ee85a6c78fcd)

**Comment by ifredom** [comment]
文档有如何保存为csv

**Comment by zycrwa** [comment]
直接设置成导出为csv不就可以了吗？
