### ISSUE TITLE
为何这个关键词在confing里面没有了，不知道为什么？

### ISSUE THREAD

**Issue by zycrwa** [NanmiCoder/MediaCrawler#259]
# 评论关键词筛选(只会留下包含关键词的评论,为空不限制)
COMMENT_KEYWORDS = [
'比亚迪'
    # ........................
]

**Comment by zycrwa** [comment]
就是现在的search的关键词在哪里

**Comment by NanmiCoder** [comment]
仓库不集成该功能了，请自行对评论过滤

**Comment by zycrwa** [comment]
好的，谢谢
