### ISSUE TITLE
保存为csv文件时，中文出现乱码

### ISSUE THREAD

**Issue by YutakaTan** [NanmiCoder/MediaCrawler#262]
![QQ截图20240505220607](https://github.com/NanmiCoder/MediaCrawler/assets/74189169/fcb0be23-f98c-4c71-82c1-be81d52637ca)
![image](https://github.com/NanmiCoder/MediaCrawler/assets/74189169/9f9ad3bc-1c8b-422c-85c9-f5a527f86015)

**Comment by NanmiCoder** [comment]
应该是工具本身的问题，换成wps打开试试
