### ISSUE TITLE
请问如何可以爬取抖音视频数据

### ISSUE THREAD

**Issue by hy-li751** [NanmiCoder/MediaCrawler#268]
根据readme提示的命令。main.py支持search、detail、creator类型，但是爬取后的数据是包含评论的json文件，没有视频数据输出，想请教如何下载视频

**Comment by NanmiCoder** [comment]
主要是视频元信息这些哈，如果要现在视频的划可以看这个哈https://github.com/Evil0ctal/Douyin_TikTok_Download_API

**Comment by hy-li751** [comment]
就是说这个代码，以爬取文本信息为主，不支持爬取视频，对吧！
