### ISSUE TITLE
如何绕开搜索量的限制？

### ISSUE THREAD

**Issue by Andy0731** [NanmiCoder/MediaCrawler#269]
请问有什么方式能绕开搜索量的限制吗？ 我跑xhs的代码只能下载20条数据，怎样能大规模的爬数据呢？感谢！

**Comment by NanmiCoder** [comment]
cofig/base_config.py中的 `CRAWLER_MAX_NOTES_COUNT`参数控制数量，默认=20
只不过现在xhs web端已经有限制了，一个keyword好像是220条。
