### ISSUE TITLE
获取到的笔记图片是有水印的，如何解析拉取到的数据呢

### ISSUE THREAD

**Issue by FirminSun** [NanmiCoder/MediaCrawler#27]
你好，
我获取到的数据地址是这样的：https://sns-img-bd.xhscdn.com/cebf4761-7ec0-9911-fbdf-77fd3cb01c31
这是一张图，如何把解析成图片呢？

我尝试下载下来，添加.jpg后缀，可以查看到图片。

另外，
获取到的笔记图片是有水印的，还是我中间有些操作不正确，导致水印没有去除？

望回复。。

**Comment by NanmiCoder** [comment]
在笔记详情响应的image_list中得到xhs图片CDN的域名，再拼接上trace_id即可，举个例子，下面截图中如果要得到无水印的图片，最终的图片地址为：https://sns-img-hw.xhscdn.com/spectrum/1000g0k02h23l6agj20005ouknt1puhr546it1l8
![image](https://github.com/NanmiCoder/MediaCrawler/assets/47178017/fcff81cb-c1cc-4fd7-823e-d92f5670d656)

**Comment by FirminSun** [comment]
> 在笔记详情响应的image_list中得到xhs图片CDN的域名，再拼接上trace_id即可，举个例子，下面截图中如果要得到无水印的图片，最终的图片地址为：https://sns-img-hw.xhscdn.com/spectrum/1000g0k02h23l6agj20005ouknt1puhr546it1l8 ![image](https://user-images.githubusercontent.com/47178017/259641236-fcff81cb-c1cc-4fd7-823e-d92f5670d656.png)

非常感谢，已经解决了。

**Comment by FirminSun** [comment]
@NanmiCoder 大大， 现在怎么解析到无水印数据呢？ 可以帮忙看看吗

**Comment by WenmuZhou** [comment]
最新的已经没有traceid了，不能拿到无水印图片了
