### ISSUE TITLE
爬取微博找不到登录按钮

### ISSUE THREAD

**Issue by xiangfeng1115** [NanmiCoder/MediaCrawler#270]
![联想截图_20240520102637](https://github.com/NanmiCoder/MediaCrawler/assets/138760624/e59cd86c-9c15-46f0-9ba2-59b08cf793ab)

login dialog box does not pop up automatically, error: Timeout 4000ms exceeded.如何解决

**Comment by Mr-pizza** [comment]
友友，请问你解决了吗，可以教我一下吗

**Comment by NanmiCoder** [comment]
fix it
