### ISSUE TITLE
请问可以提供一个对外暴露的API接口吗？方便开发Web端

### ISSUE THREAD

**Issue by HildaM** [NanmiCoder/MediaCrawler#275]
目前配置信息写死在 basic_config.py 中，每次执行脚本都需要修改代码后，再次运行 main.py。

希望提供一个动态修改配置的接口，方便一次启动后，可以多次调用

**Comment by NanmiCoder** [comment]
MediaCrawler不打算实现，如果Pro版本能问世了，会提供。

**Comment by nelzomal** [comment]
@HildaM 可以用命令行参数 配置每次运行配置。新加命令行参数可以参考 #293
