### ISSUE TITLE
有人知道小红书的cookie会过期吗?

### ISSUE THREAD

**Issue by kevinl1210** [NanmiCoder/MediaCrawler#279]
我在用小红书cookie的login方法每天自动爬取creator数据。
Cookie是我在web端chrome F12人手查找到的。
有人知道这条cookie会过期吗? 如果会的话多久过期?
谢谢!

**Comment by NanmiCoder** [comment]
会过期，具体时间这个说不清楚。

**Comment by chen-junl** [comment]
> 我在用小红书cookie的login方法每天自动爬取creator数据。 Cookie是我在web端chrome F12人手查找到的。 有人知道这条cookie会过期吗? 如果会的话多久过期? 谢谢!

你设置的cookie里面的哪个字段

![Image](https://github.com/user-attachments/assets/897322fa-f155-4594-8786-8752ee6ed98d)

**Comment by kevinl1210** [comment]
> > 我在用小红书cookie的login方法每天自动爬取creator数据。 Cookie是我在web端chrome F12人手查找到的。 有人知道这条cookie会过期吗? 如果会的话多久过期? 谢谢!
> 
> 你设置的cookie里面的哪个字段
> 
> ![Image](https://github.com/user-attachments/assets/897322fa-f155-4594-8786-8752ee6ed98d)

可以看看這篇:
https://blog.csdn.net/weixin_42918447/article/details/142954586
