### ISSUE TITLE
请问这个爬取的数据可以直接导出为csv吗？因为我在导到数据库中时遇到了挺多问题

### ISSUE THREAD

**Issue by Alanhahaer** [NanmiCoder/MediaCrawler#28]
以下是遇到的一些问题：

asyncmy.errors.OperationalError: (1054, "Unknown column 'nickname' in 'field list'")

tortoise.exceptions.OperationalError: (1054, "Unknown column 'add_ts' in 'field list'")
………………一些字段缺失（我在sql内补了一些）

tortoise.exceptions.OperationalError: (1054, "Unknown column 'image_list' in 'field list'")
（有一些python的list、dict类型的我不知道在sqln内需要设置成什么）

tortoise.exceptions.OperationalError: (1366, "Incorrect string value: '\\xF0\\x9F\\x8C\\xB0' for column 'nickname' at row 1")（我去调整了sql的collation为“utf-8_general_ci”）

asyncmy.errors.DataError: (1406, "Data too long for column 'avatar' at row 1")

tortoise.exceptions.OperationalError: (1406, "Data too long for column 'avatar' at row 1")

**Comment by NanmiCoder** [comment]
建议你可以自行实现存到csv或者excel中，实现起来应该不难，把代码丢给chatgpt就能帮到你，具体需要修改的代码位置在下面
https://github.com/NanmiCoder/MediaCrawler/blob/3ae4c5f2f42d8e016632377c48ab781c76ca0cee/models/xiaohongshu.py#L107-L113

**Comment by NanmiCoder** [comment]
已支持数据保存到CSV中，请更新代码后尝试~
