### ISSUE TITLE
通过指定帖子ID爬取微博评论时出错

### ISSUE THREAD

**Issue by LINFanxz** [NanmiCoder/MediaCrawler#283]
通过指定帖子ID爬取微博评论时出错，请问是什么原因呢？需要怎么修改呢？
ERROR [WeiboCrawler.get_note_comments] may be been blocked, err:Expecting value: line 1 column 1 (char 0)
![image](https://github.com/NanmiCoder/MediaCrawler/assets/169297613/a543fce1-0f78-4824-aeeb-4880a31d3e36)

**Comment by NanmiCoder** [comment]
已修复，请拉取最新代码尝试
