### ISSUE TITLE
CRAWLER_MAX_NOTES_COUNT 参数无法应用

### ISSUE THREAD

**Issue by Dylanmengzhou** [NanmiCoder/MediaCrawler#289]
我尝试用关键词查询小红书帖子，我将CRAWLER_MAX_NOTES_COUNT设置成50，因为我需要50个帖子，可是我发现最后只给我了20个，请问一下这个是bug还是应该设置别的参数。

**Comment by NanmiCoder** [comment]
尝试更新最新代码
