### ISSUE TITLE
抖音x-bogus现在已经彻底失效了，更换了a-bogus，目前无法抓取数据

### ISSUE THREAD

**Issue by NanmiCoder** [NanmiCoder/MediaCrawler#297]

**Comment by NanmiCoder** [comment]
相关的a_bogus参数实现，我已经完成：
关键词搜索接口：/aweme/v1/web/general/search/single/

![image](https://github.com/NanmiCoder/MediaCrawler/assets/47178017/50a18b41-58db-4a56-84f2-688dd9a51ede)

创作者作品列表接口：/aweme/v1/web/aweme/post/

![image](https://github.com/NanmiCoder/MediaCrawler/assets/47178017/a8dd61ce-88f5-44c6-9fdb-883418fedcb6)

**Comment by NanmiCoder** [comment]
现在面临的问题是，网上大家都没开源这个a_bogus算法实现，我这边如果推到MediaCrawler上可能有点风险，经过再三考虑，暂时不准备公开。

相关的分析流程以及示例代码我已经写好文章了，我建议大家根据文章里的示例代码在自己电脑上用替换MediaCrawler的参数加密部分，不商用

给出文章地址（知识星球，有门槛）：[【独创】使用Playwright获取某音a_bogus参数流程（包含加密参数分析）](https://articles.zsxq.com/id_u89al50jk9x0.html)

**Comment by lzy350593418** [comment]
> 现在面临的问题是，网上大家都没开源这个a_bogus算法实现，我这边如果推到MediaCrawler上可能有点风险，经过再三考虑，暂时不准备公开。
> 
> 相关的分析流程以及示例代码我已经写好文章了，我建议大家根据文章里的示例代码在自己电脑上用替换MediaCrawler的参数加密部分，不商用
> 
> 给出文章地址（知识星球，有门槛）：[【独创】使用Playwright获取某音a_bogus参数流程（包含加密参数分析）](https://articles.zsxq.com/id_u89al50jk9x0.html)

保存在csv文件里是什么命令呀

**Comment by NanmiCoder** [comment]
抖音已支持 Abogus参数，已恢复
