### ISSUE TITLE
不好采集二级评论吗？

### ISSUE THREAD

**Issue by png9885** [NanmiCoder/MediaCrawler#310]
二级多级评论怎么采集啊？评论时间、采集时间怎么加上啊？

**Comment by png9885** [comment]
跑了呀，看了下，跑下来的csv文档，确实没有二级评论和多层的评论，是那边操作有问题吗？

**Comment by NanmiCoder** [comment]
配置文件中有选项支持二级评论，默认不开启

png9885 ***@***.***>于2024年6月19日 周三11:29写道：
