### ISSUE TITLE
爬取一段时间后账号被封禁，如何查询被封禁时已爬取页数以便继续爬取？

### ISSUE THREAD

**Issue by xf-del** [NanmiCoder/MediaCrawler#313]
爬取一段时间后账号被封禁，如何查询被封禁时已爬取页数以便继续爬取？

**Comment by NanmiCoder** [comment]
已支持：https://github.com/NanmiCoder/MediaCrawler/commit/d3eeccbaace5b9e0d3996934d1f5870b3075096f
