### ISSUE TITLE
小红书的IP属地为什么爬不全？

### ISSUE THREAD

**Issue by cl165** [NanmiCoder/MediaCrawler#326]
只有少部分数据有IP属地，大部分用户没有爬取下来，但页面上有展示

**Comment by helloteemo** [comment]
@cl165 可以给出两个案例来吗？

**Comment by cl165** [comment]
> @cl165 可以给出两个案例来吗？

比如这个：https://www.xiaohongshu.com/user/profile/64c77f2c000000000b0064ce，页面显示有IP属地，但数据库中没有。
<img width="367" alt="image" src="https://github.com/user-attachments/assets/01bee324-dcff-4043-946b-20120ebd8c13">
<img width="727" alt="image" src="https://github.com/user-attachments/assets/a11e41bd-e57a-476b-99dd-bc94922a2c28">

**Comment by helloteemo** [comment]
> > @cl165 可以给出两个案例来吗？
> 
> 比如这个：[https://www.xiaohongshu.com/user/profile/64c77f2c000000000b0064ce，页面显示有IP属地，但数据库中没有。](https://www.xiaohongshu.com/user/profile/64c77f2c000000000b0064ce%EF%BC%8C%E9%A1%B5%E9%9D%A2%E6%98%BE%E7%A4%BA%E6%9C%89IP%E5%B1%9E%E5%9C%B0%EF%BC%8C%E4%BD%86%E6%95%B0%E6%8D%AE%E5%BA%93%E4%B8%AD%E6%B2%A1%E6%9C%89%E3%80%82) <img alt="image" width="367" src="https://private-user-images.githubusercontent.com/6203863/348449221-01bee324-dcff-4043-946b-20120ebd8c13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NzI2NDgsIm5iZiI6MTcyMDg3MjM0OCwicGF0aCI6Ii82MjAzODYzLzM0ODQ0OTIyMS0wMWJlZTMyNC1kY2ZmLTQwNDMtOTQ2Yi0yMDEyMGViZDhjMTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTNUMTIwNTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjMwMDg3MzNiMzZlMGIwZjE0MmRiMGE4NDc5ZTBlZWQzNjA4NTkyMDA1MTEyYjMyZjBmNzAwNGNlYjQwZWZmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RppyhKx05HyRQbjoPxixqavQEaaIZwEXRWBRfxoX6Dc"> <img alt="image" width="727" src="https://private-user-images.githubusercontent.com/6203863/348449232-a11e41bd-e57a-476b-99dd-bc94922a2c28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NzI2NDgsIm5iZiI6MTcyMDg3MjM0OCwicGF0aCI6Ii82MjAzODYzLzM0ODQ0OTIzMi1hMTFlNDFiZC1lNTdhLTQ3NmItOTlkZC1iYzk0OTIyYTJjMjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTNUMTIwNTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTBiMDMwMzhjODNmYzYxY2IyNWNjY2UwNTY2ZDdiYzZiNGU1N2Q0ZDE3NzdiZGZlMjNiNDAxZDA3NjY3MzAyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._KJYH3IU39sN5zIWujh63Euo_lTYWZ25IUbj7VPtD0U">

你看的这个是作者地区，数据库展示的评论的IP属地，这两者是不一样的，数据库展示的IP属地是评论人发评论那一刻的IP属地，不存在是有可能的

**Comment by helloteemo** [comment]
@cl165 如果没有其余问题建议关闭这个Issue
