### ISSUE TITLE
抖音爬虫爬取up主视频demo报错

### ISSUE THREAD

**Issue by seuchenyu** [NanmiCoder/MediaCrawler#335]
<img width="1359" alt="image" src="https://github.com/user-attachments/assets/ab7135b3-0552-4ec1-b7dd-542f37a141a5">
b站是可以爬取的，我的命令式python main.py --platform dy --lt qrcode --type creator
用的默认配置的抖音up主的那个id

**Comment by NanmiCoder** [comment]
已修复
