### ISSUE TITLE
哥们，你的作品被这个大可爱偷了😂https://github.com/jiji262/MediaCrawler-new 甚至还收获了几百个星星

### ISSUE THREAD

**Issue by oorsuioi** [NanmiCoder/MediaCrawler#338]
哥们，你的作品被这个大可爱偷了😂https://github.com/jiji262/MediaCrawler-new 甚至还收获了几百个星星

**Comment by NanmiCoder** [comment]
感谢你的提醒，这个问题可以看下我之前发的issue，很早之前就发现了，管不了，也不想管他们了。
