### ISSUE TITLE
IP代理功能失效，无论使用哪种缓存方式，过期ip都不会清理

### ISSUE THREAD

**Issue by xf-del** [NanmiCoder/MediaCrawler#339]

**Comment by NanmiCoder** [comment]
我刚查了代码，过期IP的清理跟缓存没有关系。
当前ip代理过期的原因是由于MediaCrawler原始版本当初在设计之初时，代码启动时就固定了一个IP（只会从IP代理池取一个IP一直用下去），自媒体平台都需要账号登录，所以一个IP跟账号绑定是一种更加稳定的做法。

**Comment by NanmiCoder** [comment]
在多账号版本（账号和IP配对）没有提供前，我会将当前的代理功能先移除，免得误导大家。
最开始在MediaCrawler未开源是多账号版本，所以把代理IP的功能遗留到了单账号，导致了现在的问题。
