### ISSUE TITLE
咨询，试了一下 dy 的抓取，看了下数据库内容，好像没有抓到那种评论里的回复。为了表达清楚，我截个图示意一下，谢谢。

### ISSUE THREAD

**Issue by Yi-Lyu** [NanmiCoder/MediaCrawler#34]
咨询，试了一下 dy 的抓取，看了下数据库内容，好像没有抓到那种评论里的回复。为了表达清楚，我截个图示意一下，谢谢。

如下图，我指这样的评论里的回复，爬取数据里没有爬这里面的内容，对嘛？ 
![image](https://github.com/NanmiCoder/MediaCrawler/assets/1308846/fd5ad7f5-f115-4e11-8867-71ff35830d77)

**Comment by NanmiCoder** [comment]
目前只爬取了一级评论～

**Comment by yarntime** [comment]
目前好像抓不到评论了，大神是做了什么改动吗？怎么抓到一级评论的呢？

**Comment by pooruirui** [comment]
评论的评论太动态了，这个问题我也很好奇要怎么解决，怎么抓到展开回复的请求

**Comment by Yi-Lyu** [comment]
> 

有什么好想法么？

**Comment by pooruirui** [comment]
用selenium模拟去点指定的展开回复的元素，然后判断这些元素全都不存在在进行爬取，但是逆向我不明白怎么实现这种模拟操作

**Comment by og1ocdd** [comment]
> > 
> 
> 有什么好想法么？
我是直接照搬拿一级评论的代码,修改get_aweme_all_comments,在循环里拿到一级评论后检测reply_comment_total看有没有reply,有就直接加一层循环就行了

**Comment by putianlaoshiren** [comment]
> > > 
> > 
> > 
> > 有什么好想法么？
> > 我是直接照搬拿一级评论的代码,修改get_aweme_all_comments,在循环里拿到一级评论后检测reply_comment_total看有没有reply,有就直接加一层循环就行了

这样操作可以吗
