### ISSUE TITLE
小红书在保持登录的状态下仍需扫码登录

### ISSUE THREAD

**Issue by Siji-chl** [NanmiCoder/MediaCrawler#342]
小红书，保持登陆设置为True，浏览器也显示已登录，但提示Begin login xiaohongshu by qrcode ...，且无二维码弹出

**Comment by NanmiCoder** [comment]
https://github.com/NanmiCoder/MediaCrawler/blob/548271e5373e523d8c49676a60b4c66487a03577/config/base_config.py#L21-L25
