### ISSUE TITLE
多个账号都显示account blocked

### ISSUE THREAD

**Issue by Panic-W** [NanmiCoder/MediaCrawler#349]
抖音爬取用户主页下视频的时候，换了三个账号都显示media_platform.douyin.exception.DataFetchError: account blocked，打印了response.text，是空的什么都没有。
![image](https://github.com/user-attachments/assets/bcc28dd2-2b1e-4ff6-b093-723674b3e478)

**Comment by peiqijiayou** [comment]
我也遇到这个问题，请问解决了吗

**Comment by NanmiCoder** [comment]
休整几个小时后，删除browser_data目录下对应的平台文件，重新执行登陆流程尝试。
