### ISSUE TITLE
快手搜索爬取数据时，会出现评论报错，搜索没有数据返回的情况

### ISSUE THREAD

**Issue by SDWade3** [NanmiCoder/MediaCrawler#351]
大佬，快手搜索爬取数据遇到两个问题啊，搜索了两个关键字，第一个关键字有视频数据返回，评论返回部分数据，运行多次后，评论数据不返回了，但是我看视频是有评论的。第二个搜索报找不到数据。这是啥原因嘛？我在网上找了最简单的方式是可以返回搜索数据和评论数据的。
![微信图片_20240719163915](https://github.com/user-attachments/assets/8be37f12-b5a1-4988-a7ee-73f14c045f4f)
![微信图片_20240719163924](https://github.com/user-attachments/assets/772b8f1b-c426-4def-be3f-156237a93627)

**Comment by Holmes-pengge** [comment]
![image](https://github.com/user-attachments/assets/3f1933bd-2bbf-4982-a0bf-9ac931f65b5d)
出现验证码了，大概率是爬取频率问题
