### ISSUE TITLE
每次爬抖音，都有大量IP地址为空，去到用户主页看都是有ip的

### ISSUE THREAD

**Issue by xf-del** [NanmiCoder/MediaCrawler#354]

**Comment by NanmiCoder** [comment]
评论时的IP可能会为空，这个取决于平台对评论的接口返回，若要加评论的IP，可以去主页提取。

**Comment by xf-del** [comment]
> 评论时的IP可能会为空，这个取决于平台对评论的接口返回，若要加评论的IP，可以去主页提取。

python小白还在学习中，老师能安排增加这个功能吗
