### ISSUE TITLE
小红书现在爬不了了吗

### ISSUE THREAD

**Issue by oorsuioi** [NanmiCoder/MediaCrawler#356]

**Comment by kunhai-88** [comment]
/api/sns/web/v1/feed"接口参数变了
![image](https://github.com/user-attachments/assets/13a1105b-799f-44c9-ba01-0b4d9ee79138)
需要添加 xsec_token，xsec_token  可以再搜索接口拿到

async def get_note_by_id(self, note_id: str, xsec_token: str) -> Dict:
        """
        获取笔记详情API
        Args:
            note_id:笔记ID

        Returns:

        """
        data = {"source_note_id": note_id, "extra": {"need_body_topic": "1"} ,"image_formats": ["jpg", "webp", "avif"], "xsec_source":"pc_search", "xsec_token": xsec_token}
        uri = "/api/sns/web/v1/feed"
        res = await self.post(uri, data)
        
        if res and res.get("items"):
            res_dict: Dict = res["items"][0]["note_card"]
            res_dict["note_id"] = note_id
            return res_dict
        utils.logger.error(f"[XiaoHongShuClient.get_note_by_id] get note empty and res:{res}")
        return dict()

**Comment by laienliang** [comment]
> fix it

请问怎么解决的？这个code每次都不一样的

**Comment by fruitswordman** [comment]
async def fetch_creator_notes_detail(self, note_list: List[Dict]):
        """
        Concurrently obtain the specified post list and save the data
        """
        semaphore = asyncio.Semaphore(config.MAX_CONCURRENCY_NUM)
        task_list = [
            self.get_note_detail(
                **_note_id=post_item.get("id"),_**
                xsec_source=post_item.get("xsec_source"),
                xsec_token=post_item.get("xsec_token"),
                semaphore=semaphore
            )
            for post_item in note_list
        ]

        note_details = await asyncio.gather(*task_list)
        for note_detail in note_details:
            if note_detail:
                await xhs_store.update_xhs_note(note_detail)

此处 **_note_id=post_item.get("id"),_**是不是应该是**_note_id=post_item.get("note_id"),_**呀

新update后的代码运行会报 source_note_id not found的报错，我追踪到这里，尝试修改以后就能跑通了。麻烦作者大大check一下

**Comment by NanmiCoder** [comment]
> ```
> async def fetch_creator_notes_detail(self, note_list: List[Dict]):
>     """
>     Concurrently obtain the specified post list and save the data
>     """
>     semaphore = asyncio.Semaphore(config.MAX_CONCURRENCY_NUM)
>     task_list = [
>         self.get_note_detail(
>             note_id=post_item.get("id"),
>             xsec_source=post_item.get("xsec_source"),
>             xsec_token=post_item.get("xsec_token"),
>             semaphore=semaphore
>         )
>         for post_item in note_list
>     ]
> 
>     note_details = await asyncio.gather(*task_list)
>     for note_detail in note_details:
>         if note_detail:
>             await xhs_store.update_xhs_note(note_detail)
> ```
> 
> 此处 **_note_id=post_item.get("id"),_** 是不是应该是 **_note_id=post_item.get("note_id"),_** 呀
> 
> 新update后的代码运行会报 source_note_id not found的报错，我追踪到这里，尝试修改以后就能跑通了。麻烦作者大大check一下

确实有问题，你可以贡献代码，但是修复这个 bug 的时候，复制错了。

**Comment by fruitswordman** [comment]
#360 
提交了pull request啦大大😊

**Comment by NanmiCoder** [comment]
> #360 提交了pull request啦大大😊

已合，感谢贡献

**Comment by Ang0426** [comment]
麻烦问一下xsec_token这个东西是怎么获取的，没太理解，多谢多谢

**Comment by Deliayiyiyi** [comment]
在小红书首页抓取content_id和xsec_token，组成链接www.xiaohongshu.com/explore/{content_id}?xsec_token={xsec_token}&xsec_source=pc_search，可以较为稳定地直接跳转到帖子，但是xsec_token会变，一人知道这个变化是随机还是有规律性的吗？比如有一个时效性，或者是进入链接过于频繁会修改token之类的？有什么解决的办法吗？

**Comment by freemedom** [comment]
看来目前是无解了，仅凭content_id无法获得xsec_token，必须搜索关键词，在搜索结果获得xsec_token

**Comment by freemedom** [comment]
https://github.com/NanmiCoder/MediaCrawler/issues/382
