### ISSUE TITLE
抖音无法登陆

### ISSUE THREAD

**Issue by og1ocdd** [NanmiCoder/MediaCrawler#36]
dy不管使用哪种方法登录都同样报错,xhs正常
-------
好像是playwright的问题,我这边用playwright无法打开抖音首页,把index_url换成www.douyin.com/discover
就正常了

**Comment by NanmiCoder** [comment]
我这边尝试是可以的，可能是你那边次数多了之后，dy 会有一定的限制，可以隔段时间之后再尝试下，能否登录
