### ISSUE TITLE
dy指定id评论

### ISSUE THREAD

**Issue by Runnnnnnnnn** [NanmiCoder/MediaCrawler#363]
是否可以爬取指定ID的所有抖音评论呢

**Comment by NanmiCoder** [comment]
看看config配置文件中，有哈

**Comment by Runnnnnnnnn** [comment]
不好意思，可能我没描述清楚，我是指某一用户在抖音上的所有评论，是否可以通过该用户的ID去爬取到。也许你回答的是可以，主要是我不知道怎么去更改设置，望指教，谢谢

**Comment by NanmiCoder** [comment]
没有
