### ISSUE TITLE
xhs登录二维码能否在terminal里显示

### ISSUE THREAD

**Issue by hepengfe** [NanmiCoder/MediaCrawler#368]
由于我ssh的server没有GUI可以显示, 所以我想问下xhs登录二维码能否在terminal里显示

**Comment by NanmiCoder** [comment]
之前考虑过集成，但是后面遇到了即使扫码通过了，平台方还会有滑块验证，还得浏览器手工滑动，所以就没考虑Linux使用qrcode的方案了。
