### ISSUE TITLE
小红书-评论请求-新增X-S参数校验

### ISSUE THREAD

**Issue by webberDavid** [NanmiCoder/MediaCrawler#369]
自动2024-07,7月末开始小红书的评论请求里,header新增了X-S参数的校验,仅凭cookie拿不到评论数据了
![image](https://github.com/user-attachments/assets/b7f77e3b-e239-47d7-ac8c-4e4dfd8640e3)
![image](https://github.com/user-attachments/assets/0bf8a96c-0f4f-4f26-849a-c938f37a3f8f)

**Comment by NanmiCoder** [comment]
你发这个issue是有什么问题吗，MediaCrawler评论一直都用的是X-s啊
