### ISSUE TITLE
 (venv) D:\MediaCrawler>pip3 install -r requirements.txt ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'       总是报错，有什么问题嘛

### ISSUE THREAD

**Issue by RICKDONG123** [NanmiCoder/MediaCrawler#381]
(venv) D:\MediaCrawler>pip3 install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'       总是报错，有什么问题嘛

**Comment by NanmiCoder** [comment]
报错已经很明显了，路径不对，确认是否在MediaCrawler根目录下。
