### ISSUE TITLE
请问XHS可以进行关键字搜索嘛

### ISSUE THREAD

**Issue by SerMs** [NanmiCoder/MediaCrawler#39]

**Comment by NanmiCoder** [comment]
默认就是以关键字来搜索笔记的。

**Comment by zhouayi** [comment]
关键字修改在base_config.py中的KEYWARDS

**Comment by luanshils** [comment]
> 默认就是以关键字来搜索笔记的。

请问可以只在某个固定USER_ID用户页里面对所有笔记评论进行爬取吗?

**Comment by luanshils** [comment]
> 默认就是以关键字来搜索笔记的。

请问可以只在某个固定USER_ID用户页里面对所有笔记评论进行爬取吗?
