### ISSUE TITLE
douyin通过关键词爬取数据，只返回2页数据，第3页开始返回的数据为空

### ISSUE THREAD

**Issue by SummerChris** [NanmiCoder/MediaCrawler#391]
如题，一开始未设置睡眠时间，只有第1页返回数据，后面在代码中设置睡眠时间（看截图），第2页有数据返回，但从第3页开始又无法返回数据了。
![06b9406747a683c56fbc58ed7c5e77c](https://github.com/user-attachments/assets/80d08a26-4c50-49b9-9795-32b6fa9a0108)
![3c7764631536323d9c36bf2ed926316](https://github.com/user-attachments/assets/d4ed71d7-ee30-4099-86e6-e474e4d5fb9e)

**Comment by TREEee14ee** [comment]
我也遇到了同样的问题，请问你解决这个问题了吗？

**Comment by NanmiCoder** [comment]
待修复

**Comment by NanmiCoder** [comment]
已修复，拉取最新代码
