### ISSUE TITLE
小红书爬取的相关数据之前可以精确到个位数，最近好像不太行了，请问有什么办法吗？麻烦了

### ISSUE THREAD

**Issue by unbie** [NanmiCoder/MediaCrawler#393]
![微信图片_20240815161828](https://github.com/user-attachments/assets/dcd92142-c426-4978-bd7c-970f3a677062)

**Comment by NanmiCoder** [comment]
详情模式直接通过API的方式不可以了，目前是通过解析html文档的当时得到提帖子详情

**Comment by unbie** [comment]
好的，非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月15日(星期四) 晚上7:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [NanmiCoder/MediaCrawler] 小红书爬取的相关数据之前可以精确到个位数，最近好像不太行了，请问有什么办法吗？麻烦了 (Issue #393)














 
详情模式直接通过API的方式不可以了，目前是通过解析html文档的当时得到提帖子详情
