### ISSUE TITLE
如何保存到PGSQL

### ISSUE THREAD

**Issue by ericzhang-debug** [NanmiCoder/MediaCrawler#398]
如题，README中写了支持，请问如何配置，还是说需要自己手动实现？

![QQ_1724050844866](https://github.com/user-attachments/assets/7b5742a2-2467-4cd0-8edf-280568aaff27)

**Comment by NanmiCoder** [comment]
不好意思，现在的版本不支持了，之前有ORM的时候支持

**Comment by NanmiCoder** [comment]
需要自己实现

**Comment by ericzhang-debug** [comment]
> 需要自己实现

在不改变暴露函数名的情况下只需要修改db.py和async_db.py吗？

**Comment by NanmiCoder** [comment]
对
