### ISSUE TITLE
增加的新功能：小红书发布评论，虽然Post正常，但是reponse里的status不是0，而是-1, 2等，导致评论无法展示。请问如果改为status =0

### ISSUE THREAD

**Issue by Justincyz** [NanmiCoder/MediaCrawler#403]
{
      "id":"xxxxxx",
      "note_id":"xxxxx",
      "at_users":[
         
      ],
      "create_time":1724222472000,
      "sub_comment_count":"0",
      "like_count":"0",
      "user_info":{
         "user_id":"xxxxxxx",
         "nickname":"xxxxxx",
         "image":"https://sns-avatar-qc.xhscdn.com/avatar/xxxxxxxxx?imageView2/2/w/120/format/jpg"
      },
      "show_tags":[
         
      ],
      "ip_location":"广东",
      "content":"1513",
      "liked":false,
      "sub_comments":[
         
      ],
      "sub_comment_has_more":false,
      **_"status":-1,_**
      "sub_comment_cursor":""
   },

**Comment by NanmiCoder** [comment]
发布评论等不会支持

**Comment by NanmiCoder** [comment]
有需要的可以参考这个仓库：https://github.com/ReaJason/xhs

**Comment by Justincyz** [comment]
> 有需要的可以参考这个仓库：https://github.com/ReaJason/xhs

看过这个仓库，思路是一样的。我上小红书查了他们对code的描述(https://school.xiaohongshu.com/en/open/product/product-status.html)，应该是有问题。只有status为0才会被展示出来，但是奇怪的是post也是正常的。
