### ISSUE TITLE
小红书获取帖子详情时，浏览器异常，请尝试关闭/卸载风险插件或重启试试

### ISSUE THREAD

**Issue by SongweiCao** [NanmiCoder/MediaCrawler#407]
![image](https://github.com/user-attachments/assets/b0949880-ba8f-4369-be5d-e3dad253c5d4)

**Comment by NanmiCoder** [comment]
是仓库的代码没做任何更改吗，我这里没能复现你的问题

**Comment by SongweiCao** [comment]
> 是仓库的代码没做任何更改吗，我这里没能复现你的问题
是的，可能是xhs那边封了，这边休息一段时间就不报错了

**Comment by rocymp** [comment]
遇到同样的问题

**Comment by NanmiCoder** [comment]
看下他的回复。休息一段时间就可以了
