### ISSUE TITLE
小红书CRAWLER_TYPE = "creator" 失效

### ISSUE THREAD

**Issue by mjhbgt** [NanmiCoder/MediaCrawler#415]
不管XHS_CREATOR_ID_LIST设置什么博主ID，get_notes_by_creator 都无法获得数据，控制台打印出
[XiaoHongShuClient.get_notes_by_creator] The current creator may have been banned by xhs, so they cannot access the data.
调试到request方法，发现返回的是'{"code":0,"success":true,"msg":"成功","data":{}}'，没有数据
![image](https://github.com/user-attachments/assets/5b48909e-d32f-425d-b737-c4d2ab0ea74f)

**Comment by NanmiCoder** [comment]
我这里测试了没发现该问题，请确认下账号本身的问题

**Comment by QQuinn03** [comment]
我有同样的问题，无论怎么换XHS_CREATOR_ID 都显示“The current creator may have been banned by xhs, so they cannot access the data.“
