### ISSUE TITLE
xhs 获取详情出错

### ISSUE THREAD

**Issue by NanmiCoder** [NanmiCoder/MediaCrawler#423]
<img width="1545" alt="image" src="https://github.com/user-attachments/assets/8b3213b7-147d-4286-9d02-79cfe1f6bc99">

**Comment by NanmiCoder** [comment]
原获取详情API方法可能由于playwright版本的x-s签名算法，导致被检测了，估下面的方法已失效。

https://github.com/NanmiCoder/MediaCrawler/blob/d6fb255bdff66cd1cb99ecee4b4822ac21a43432/media_platform/xhs/client.py#L202-L230

最新代码使用：get_note_by_id_from_html 获取帖子详情。

**Comment by mjhbgt** [comment]
原来的get_note_by_id方法，多少还能抓到一部分，新的get_note_by_id_from_html总是会拿到一个页面跳转，导致数组[0]越界异常
        url = "https://www.xiaohongshu.com/explore/" + note_id
        html = await self.request(method="GET", url=url, return_response=True, headers=self.headers)
        state = re.findall(r"window.__INITIAL_STATE__=({.*})</script>", html)[0].replace("undefined", '""')

**Comment by NanmiCoder** [comment]
经过测试get_note_by_id也可以用，不传sec_token

**Comment by Mirror-empty** [comment]
> > 经过测试get_note_by_id也可以用，不传sec_token
> 
> 不传sec_token、xsec_source倒是可以用，不过不多久还是被控，之前没这情况

被控了多久？我测试看需要一天才能解封

**Comment by IianWang** [comment]
> > > 经过测试get_note_by_id也可以用，不传sec_token
> > 
> > 
> > 不传sec_token、xsec_source倒是可以用，不过不多久还是被控，之前没这情况
> 
> 被控了多久？我测试看需要一天才能解封

几小时 ~ 一天，具体看情况
