### ISSUE TITLE
xhs type=creator 正常爬取一段时间出现访问频次异常，请问有什么办法吗？麻烦了

### ISSUE THREAD

**Issue by unbie** [NanmiCoder/MediaCrawler#424]
![Snipaste_2024-09-03_14-45-25](https://github.com/user-attachments/assets/e6c7cad6-dce0-4dde-a61e-3aac1a49f100)

**Comment by NanmiCoder** [comment]
没有哈

**Comment by QIANJUFEN** [comment]
试试停顿一段时间
