### ISSUE TITLE
配置db，连接mysql8报错"Can't connect to MySQL server on '127.0.0.1'"

### ISSUE THREAD

**Issue by ryonWang** [NanmiCoder/MediaCrawler#430]
db配置了，数据库也手动创建了，但是连接mysql8报错"Can't connect to MySQL server on '127.0.0.1'"，我有个怀疑是参数是否需要加SSL或者要配置套接字？我尝试写死db.py也还是不行。有没有人遇到同样问题？
![13851725529823_ pic](https://github.com/user-attachments/assets/d0513a1e-f955-469c-801e-911d5c548b12)
![13861725529863_ pic](https://github.com/user-attachments/assets/64f15596-6a56-4eaa-aa14-3b0fd1d5d188)

**Comment by NanmiCoder** [comment]
<img width="995" alt="image" src="https://github.com/user-attachments/assets/f0996297-6766-4fe2-af70-80364ea29659">
使用原本的配置没有问题，请确认自己修改的原因。
