### ISSUE TITLE
抖音登录后运行失败

### ISSUE THREAD

**Issue by cnguu** [NanmiCoder/MediaCrawler#434]
python main.py --platform dy --lt qrcode --type detail

![image](https://github.com/user-attachments/assets/77d410ca-10a5-442f-af7c-d970977ba721)

**Comment by Glksky** [comment]
是直接跑的代码吗 为什么我check login的时候就失败了 小红书没有问题 抖音的不行

**Comment by NanmiCoder** [comment]
经排查，使用playwright获取abogus参数的方式已失效，目前还没发现使用playwright获取的新方法。

https://github.com/NanmiCoder/MediaCrawler/blob/21e0d8f393119225adbe61cd26d2434ab2dc51e5/media_platform/douyin/help.py#L48-L51

如果着急的话可以看下[MediaCrawlerPro](https://github.com/MediaCrawlerPro)，因为它移除了playwright的依赖所有没有这个问题。

**Comment by pcvc** [comment]
抖音不行了，，，

**Comment by NanmiCoder** [comment]
已支持
