### ISSUE TITLE
抖音登入失败

### ISSUE THREAD

**Issue by Glksky** [NanmiCoder/MediaCrawler#436]
![image](https://github.com/user-attachments/assets/f3021c8b-8828-40d9-a1ec-5c261a32d419)
抖音爬虫的时候登入失败

**Comment by NanmiCoder** [comment]
经排查，使用playwright获取abogus参数的方式已失效，目前还没发现使用playwright获取的新方法。

https://github.com/NanmiCoder/MediaCrawler/blob/21e0d8f393119225adbe61cd26d2434ab2dc51e5/media_platform/douyin/help.py#L48-L51

如果着急的话可以看下[MediaCrawlerPro](https://github.com/MediaCrawlerPro)，因为它移除了playwright的依赖所有没有这个问题。

**Comment by NanmiCoder** [comment]
已支持
