### ISSUE TITLE
dy 爬取指定帖子详情时，报错

### ISSUE THREAD

**Issue by maturest** [NanmiCoder/MediaCrawler#442]
1、先看报错内容

![微信图片_20240921164927](https://github.com/user-attachments/assets/4d8b54c3-7ca1-4173-a63c-af75cda282a9)

2、盲猜应该是 dy 前端 js 版本更新导致的。

**Comment by NanmiCoder** [comment]
https://github.com/NanmiCoder/MediaCrawler/issues/437

**Comment by NanmiCoder** [comment]
已支持
