### ISSUE TITLE
登录已过期

### ISSUE THREAD

**Issue by jack206418070** [NanmiCoder/MediaCrawler#45]
請問大佬, 我使用 掃碼登入或者cookie登入
可以順利登入
不過當開始抓取不到一組資料的時候
就會直接被登出顯示以下資訊
media_platform.xhs.exception.DataFetchError: 登录已

是為什麼呢？

**Comment by NanmiCoder** [comment]
每一个账号获取到一定数据量之后会被风控，隔段时间这个账号才能从新使用。

**Comment by jack206418070** [comment]
非常感謝～

**Comment by Morriaty-The-Murderer** [comment]
请问下“隔段时间”，这个按经验来说，大约是多久呢
