### ISSUE TITLE
大家的 xhs 爬取多少会被控？

### ISSUE THREAD

**Issue by yinzhou-jc** [NanmiCoder/MediaCrawler#459]
我先来，5 个 IP pool，爬 120 条就被控了。
是不是跟账号更相关，跟 ip 关系不大？

**Comment by csdogww** [comment]
我也很想知道为什么....

**Comment by 522109452** [comment]
最近风控有点严

**Comment by leezomtang** [comment]
同样的遭遇，爬了100多条就被控了

**Comment by jimmycmh** [comment]
按账号的，跟ip关系不大。连续爬200个左右就不行了，一直如此

**Comment by csdogww** [comment]
那账号访问限制是指达到200个左右之后就永久无法继续下载，还是说过一段时间会重置一下，复原权限

**Comment by cresstoo** [comment]
2个IP池爬了90条就开始`MediaCrawler ERROR (core.py:309) - [XiaoHongShuCrawler.get_note_detail_async_task] Get note detail error`

**Comment by dbcooper7z** [comment]
python main.py --platform xhs --lt cookie --type creator，爬取300条后，提示”访问频次异常，请勿频繁操作或重启试试“。
下一次运行如何避免从头开始爬取，是否可以从上一次中断的地方继续爬取？
