### ISSUE TITLE
小红书以detail模式爬取会出现识别完帖子id后卡住的现象

### ISSUE THREAD

**Issue by wxy123jy** [NanmiCoder/MediaCrawler#469]
想问下大家在这次更新后小红书以detail模式爬取会出现识别完帖子id后卡住的现象吗？
图片是我出现问题的地方，读取完id后就不动了，然后就报错list index out of range,请大佬指教
![微信图片_20241027230409](https://github.com/user-attachments/assets/9a2f6312-71b6-40af-83db-b432d7cca183)
![微信图片_20241027230416](https://github.com/user-attachments/assets/d22e663d-d84f-462a-ad5e-32865c2819ec)

**Comment by wxy123jy** [comment]
是因为从代理平台上拿到的ip访问小红书失败了吗，有点懵，偶尔就能成功一次，但是经常性的会报这个错误

**Comment by wxy123jy** [comment]
![image](https://github.com/user-attachments/assets/81892882-d5e4-4b3b-a4c1-555f37550213)
请大佬指教

**Comment by NanmiCoder** [comment]
先把代理IP去掉试试

**Comment by wxy123jy** [comment]
谢谢江哥，经测试去掉代理IP确实可以了，但是如果不用代理的话感觉很快本机就会被封，想再请问下这种情况是彻底不能用代理了吗？想继续使用代理的话该怎么实现呢

**Comment by NanmiCoder** [comment]
https://github.com/NanmiCoder/MediaCrawler/issues/455

可以看下上面这个issue

Wxy ***@***.***>于2024年10月28日 周一17:14写道：

**Comment by wxy123jy** [comment]
谢谢江哥，在您的code里学到了很多，我会持续关注更新
