### ISSUE TITLE
get comments failed, error: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by fulaoban** [NanmiCoder/MediaCrawler#47]
get comments failed, error: Expecting value: line 1 column 1 (char 0)
其它博主下面的评论 就没事，某一个就不行，不知道杂回事

**Comment by luanshils** [comment]
是不是爬不全评论，我也遇到了

**Comment by NanmiCoder** [comment]
> get comments failed, error: Expecting value: line 1 column 1 (char 0) 其它博主下面的评论 就没事，某一个就不行，不知道杂回事

如果是抖音的出现这个有可能是账号爬去一定数量后被风控了，需要等这个账号解除风控，或者尝试更换你的账号
