### ISSUE TITLE
小红书会出现获取失败或者461报错

### ISSUE THREAD

**Issue by MandyHenderson** [NanmiCoder/MediaCrawler#470]
![image](https://github.com/user-attachments/assets/bafdb1f4-ea98-4bd3-8113-ae6c510e7e32)

**Comment by MandyHenderson** [comment]
![image](https://github.com/user-attachments/assets/35267072-ace8-4929-9090-96c24847cc60)
后面开始登陆了显示还得登录，或者有验证码验证但是在模拟的浏览器中不出现验证码

**Comment by MandyHenderson** [comment]
![image](https://github.com/user-attachments/assets/d0247af4-e986-448a-a32d-54b3c3d4918f)
buzhid网路也没问题号也正常

**Comment by NanmiCoder** [comment]
删除Browser_data目录，再试

**Comment by MandyHenderson** [comment]
> 删除Browser_data目录，再试

依旧没用还是报错，甚至把项目整个重新布置了

**Comment by NanmiCoder** [comment]
梯子没开是吧，如果梯子没开的情况下，当前账号在搜索时还发生461则证明账号已经临时性被控了，更换账号再试试，我用我自己的账号测试了，能跑。

**Comment by NanmiCoder** [comment]
https://github.com/NanmiCoder/MediaCrawler/pull/479
