### ISSUE TITLE
小红书功能反馈

### ISSUE THREAD

**Issue by luanshils** [NanmiCoder/MediaCrawler#48]
请问能不能更新一个，只从固定用户主页搜索全部笔记的功能。
另外，好像笔记下的评论不能完全爬取保存完整。
不过确实挺好用的，是我找了这么多，唯一可以用的项目

**Comment by luanshils** [comment]
我看了下想要保存的评论，是一级评论，但是就是没下载到

**Comment by NanmiCoder** [comment]
默认是保存一级评论的，爬去一个帖子的所有评论在代码里也有的，改一下就 OK 了，这个函数签名中有标志位，可选择开启小红书的所有评论爬去，https://github.com/NanmiCoder/MediaCrawler/blob/7698c41d51042b4d48fdd266ba1f964e263ae159/media_platform/xhs/client.py#L173-L182

**Comment by luanshils** [comment]
> 默认是保存一级评论的，爬去一个帖子的所有评论在代码里也有的，改一下就 OK 了，这个函数签名中有标志位，可选择开启小红书的所有评论爬去，
> 
> https://github.com/NanmiCoder/MediaCrawler/blob/7698c41d51042b4d48fdd266ba1f964e263ae159/media_platform/xhs/client.py#L173-L182

感谢大佬的回复，对于评论，我再好好研读一下代码。然后，其实我现在没弄明白的是怎么单独在单一的用户  下的笔记进行爬取所有笔记。我看大佬写的都是根据关键词检索出的相关笔记。

**Comment by NanmiCoder** [comment]
> > 默认是保存一级评论的，爬去一个帖子的所有评论在代码里也有的，改一下就 OK 了，这个函数签名中有标志位，可选择开启小红书的所有评论爬去，
> > https://github.com/NanmiCoder/MediaCrawler/blob/7698c41d51042b4d48fdd266ba1f964e263ae159/media_platform/xhs/client.py#L173-L182
> 
> 感谢大佬的回复，对于评论，我再好好研读一下代码。然后，其实我现在没弄明白的是怎么单独在单一的用户 下的笔记进行爬取所有笔记。我看大佬写的都是根据关键词检索出的相关笔记。

在 xhs web 端可以轻松抓包得到一个用户下的笔记的 http 请求，改改代码就可以了，函数的 sign 签名都是一样的套路

**Comment by luanshils** [comment]
> > > 默认是保存一级评论的，爬去一个帖子的所有评论在代码里也有的，改一下就 OK 了，这个函数签名中有标志位，可选择开启小红书的所有评论爬去，
> > > https://github.com/NanmiCoder/MediaCrawler/blob/7698c41d51042b4d48fdd266ba1f964e263ae159/media_platform/xhs/client.py#L173-L182
> > 
> > 
> > 感谢大佬的回复，对于评论，我再好好研读一下代码。然后，其实我现在没弄明白的是怎么单独在单一的用户 下的笔记进行爬取所有笔记。我看大佬写的都是根据关键词检索出的相关笔记。
> 
> 在 xhs web 端可以轻松抓包得到一个用户下的笔记的 http 请求，改改代码就可以了，函数的 sign 签名都是一样的套路

好的大佬

**Comment by flyysquirrel** [comment]
能从用户 id 获得所有帖子吗?
在网页端似乎只能拿到前几条帖子
