### ISSUE TITLE
请问在哪里初始化快代理的示例呢？在那个模块哪个文件下

### ISSUE THREAD

**Issue by Dabiaoge111** [NanmiCoder/MediaCrawler#482]
初始化一个快代理的示例，如下代码所示，需要4个参数

python

def new_kuai_daili_proxy() -> KuaiDaiLiProxy:
    """
    构造快代理HTTP实例
    Returns:

    """
    return KuaiDaiLiProxy(
        kdl_secret_id=os.getenv("kdl_secret_id", "你的快代理secert_id"),
        kdl_signature=os.getenv("kdl_signature", "你的快代理签名"),
        kdl_user_name=os.getenv("kdl_user_name", "你的快代理用户名"),
        kdl_user_pwd=os.getenv("kdl_user_pwd", "你的快代理密码"),
    )

**Comment by NanmiCoder** [comment]
https://github.com/NanmiCoder/MediaCrawler/blob/3567193a9814adc479fcddb26a34eed5c5027794/proxy/providers/kuaidl_proxy.py#L134-L144
