### ISSUE TITLE
访问链接异常

### ISSUE THREAD

**Issue by ganjunjie1995** [NanmiCoder/MediaCrawler#488]
2024-11-07  21:20:58 MediaCrawler ERROR [XiaoHongShuCrawler.get_note_detail] Get note detail error: 访问链接异常

**Comment by NanmiCoder** [comment]
完整日志，可能是出现验证码了

**Comment by Double2016** [comment]
手动输验证码了，但是一直在弹窗验证不能继续爬

**Comment by NanmiCoder** [comment]
> 手动输验证码了，但是一直在弹窗验证不能继续爬

手动弹窗代码已移除，拉取最新代码尝试

**Comment by NanmiCoder** [comment]
https://github.com/NanmiCoder/MediaCrawler/issues/487#issuecomment-2506969846
