### ISSUE TITLE
小红书扫码失败了

### ISSUE THREAD

**Issue by licesun** [NanmiCoder/MediaCrawler#49]
今天开始，小红书扫码无法登陆，弹出图片，扫码，直接提示失败，重新登录，然后就是二维码过期了。

**Comment by eadwin** [comment]
+1

**Comment by NanmiCoder** [comment]
我这边测试是 OK 的，有可能是你的账号被风控了
<img width="1584" alt="image" src="https://github.com/NanmiCoder/MediaCrawler/assets/47178017/1d3ccbd5-bf41-4aa4-8afd-a77cdd736ca1">

**Comment by luanshils** [comment]
> 今天开始，小红书扫码无法登陆，弹出图片，扫码，直接提示失败，重新登录，然后就是二维码过期了。

手机重新登陆看看|

**Comment by guoqunabc** [comment]
出现类似情况，反复二维码过期

**Comment by vico1118** [comment]
> 出现类似情况，反复二维码过期

我也是这种情况。顺便问一下小红书是不是不能使用Cookies登录，我直接用Cookies会被判断为登录信息为空

**Comment by pooruirui** [comment]
先在普通网页登录一下，然后再通过这个程序登录
