### ISSUE TITLE
小红书搜索返回406

### ISSUE THREAD

**Issue by jimmycmh** [NanmiCoder/MediaCrawler#491]
最近关键词搜索都会返回406，不知道新加了什么防抓机制。

神奇的是浏览器里抓到的url，curl也会返回406

有人知道怎么解决吗

**Comment by jimmycmh** [comment]
自问自答。
小红书对搜索接口新增了header校验

            "sec-ch-ua-platform": "macOS",
            "sec-ch-ua": '"Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"',
            "sec-ch-ua-mobile": "?0",
            "x-xray-traceid": "xxxxxxxxxxxx"

另外，chrome里拷贝的curl命令不含cookie，所以失败了

**Comment by Luis-lsy** [comment]
请问你有没有爬分页的爬取，爬第二页也会406，header保持和第一页爬取一样的
