### ISSUE TITLE
raise ProgramError(value) execjs._exceptions.ProgramError: SyntaxError: 缺少 ')'

### ISSUE THREAD

**Issue by chaseyoe** [NanmiCoder/MediaCrawler#497]
这个是什么问题，是库版本依赖有问题吗？
raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: 缺少 ')'

**Comment by NanmiCoder** [comment]
[常见问题](https://nanmicoder.github.io/MediaCrawler/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98.html)
