### ISSUE TITLE
Help for config

### ISSUE THREAD

**Issue by ChloeC857** [NanmiCoder/MediaCrawler#499]
xhs怎么爬帖子type为normal而不是video的数据呢？config文件没有找到这个参数TT

**Comment by NanmiCoder** [comment]
这个参数没有在config中配置，需要修改代码实现。

#### 函数定义位置
https://github.com/NanmiCoder/MediaCrawler/blob/de32d068155d652c525ad9d66b0980879b4b38e0/media_platform/xhs/client.py#L192-L220

#### 调用方
https://github.com/NanmiCoder/MediaCrawler/blob/de32d068155d652c525ad9d66b0980879b4b38e0/media_platform/xhs/core.py#L125-L129

**Comment by ChloeC857** [comment]
已解决，在media_platform/xhs/core.py#L130修改.ALL即可，格式参考同目录field.py
