### ISSUE TITLE
请问有方法可以爬取标签以及对应的热度吗？

### ISSUE THREAD

**Issue by Qxxxx** [NanmiCoder/MediaCrawler#5]
大佬你好，

想请问一下有没有可能把 #标签 这类的话题 浏览次数 爬下来啊？类似下图这种![Screenshot_20230620_152644.jpg](https://github.com/NanmiCoder/MediaCrawler/assets/10084303/58e35beb-2a16-480e-9f0a-854a534894a2)

**Comment by NanmiCoder** [comment]
API地址是这个：https://edith.xiaohongshu.com/web_api/sns/v1/search/topic
参数：{"keyword":"健身","suggest_topic_request":{"title":"","desc":"#健身"},"page":{"page_size":20,"page":1}}
