### ISSUE TITLE
小红书详情获取不了评论了，报 “访问链接异常” 了

### ISSUE THREAD

**Issue by comdotwang162** [NanmiCoder/MediaCrawler#505]

**Comment by 522109452** [comment]
嗯，获取评论接口增加了风控参数校验

**Comment by comdotwang162** [comment]
> 嗯，获取评论接口增加了风控参数校验

大佬有解法么？

**Comment by hezhenfan** [comment]
我看作者把这个问题归结为风控问题，意思是不能通过破解参数的方式解决吗？要通过换IP或者账号的方式解决？

**Comment by hezhenfan** [comment]
> _No description provided._

好吧 我看了一下，之前是可以直接通过note_id抓取指定笔记的评论，现在只能在搜索出笔记后，带上xsec_token抓取评论

**Comment by liuminghao1** [comment]
> 我看作者把这个问题归结为风控问题，意思是不能通过破解参数的方式解决吗？要通过换IP或者账号的方式解决？

哪个接口？怎么请求啊？

**Comment by liuminghao1** [comment]
> > _No description provided._
> 
> 好吧 我看了一下，之前是可以直接通过note_id抓取指定笔记的评论，现在只能在搜索出笔记后，带上xsec_token抓取评论


哪个接口？怎么请求啊？

**Comment by hezhenfan** [comment]
> > > _No description provided._
> > 
> > 
> > 好吧 我看了一下，之前是可以直接通过note_id抓取指定笔记的评论，现在只能在搜索出笔记后，带上xsec_token抓取评论
> 
> 哪个接口？怎么请求啊？

搜索接口 每个笔记带个xsec_token

**Comment by NanmiCoder** [comment]
拉取最新代码
