### ISSUE TITLE
python main.py --platform xhs --lt qrcode --type search 命令行执行时缺少库  import httpx ModuleNotFoundError: No module named 'httpx'

### ISSUE THREAD

**Issue by dannishushu** [NanmiCoder/MediaCrawler#518]
**按照顺序执行，都没有问题，python版本是3.9.6**

  ```shell
   cd MediaCrawler
 
   python -m venv venv
   
   source venv/bin/activate

  
   pip install -r requirements.txt

 
   playwright install
   

   python main.py --platform xhs --lt qrcode --type search
   ```

出现问题如下：

(venv) x@MacBook-Air PythonProject % python main.py --platform xhs --lt qrcode --type search
Traceback (most recent call last):
  File "/Users/x/PycharmProjects/PythonProject/main.py", line 4, in <module>
    import cmd_arg
  File "/Users/x/PycharmProjects/PythonProject/cmd_arg/__init__.py", line 3, in <module>
    from .arg import *
  File "/Users/x/PycharmProjects/PythonProject/cmd_arg/arg.py", line 7, in <module>
    from tools.utils import str2bool
  File "/Users/x/PycharmProjects/PythonProject/tools/utils.py", line 4, in <module>
    from .crawler_util import *
  **File "/Users/x/PycharmProjects/PythonProject/tools/crawler_util.py", line 11, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'**

在pycharm里debug模式没有问题，但命令行执行时python main.py 就会报错缺少httpx，可是httpx已经安装了，并且版本确实是0.24.0

**Comment by NanmiCoder** [comment]
这种问题请自查，不属于MediaCrawler仓库问题范畴。

**Comment by NanmiCoder** [comment]
这个和仓库没有什么关系的，是你的mac系统python环境问题，你的虚拟环境虽然装了httpx且看起来进了虚拟环境，但是实际的运行的python不是你的虚拟环境的，临时解决方案：直接全局install，然后你要去谷歌搜索下你这个问题的解决方案。
