### ISSUE TITLE
视频爬取

### ISSUE THREAD

**Issue by Shiny-ZhangXiXin** [NanmiCoder/MediaCrawler#53]
作者你好，感谢开源代码，看到代码里面现在是爬取评论和笔记，如果想要爬取小红书或者抖音平台中的视频在哪个部分呢，现在代码中有吗~

**Comment by NanmiCoder** [comment]
你是指下载视频，还是爬去视频的列表部分呢，如果是后者的话，应该是能爬去到视频信息的。

**Comment by vico1118** [comment]
抖音下载视频作者保留了一个函数是get_video_by_id，主要是通过aweme_id获取视频详情。返回的结果可以通过res.get('aweme_detail', {}).get('video', {}).get('download_addr', {}).get('url_list', [])获取视频地址列表，列表中找到http://v3-web.douyinvod.com开头的直接请求就可以下载了（这部分需要自己实现）。小红书暂时不清楚。

**Comment by vico1118** [comment]
> 我本意是想说下载视频，比如是否能够爬取到关键词相关的视频链接列表呢。爬取视频列表是指的什么呢？是说视频的评论信息吗。但是我看代码中主要实现的是爬取笔记和爬取笔记的评论两个基准类。

抖音下载视频作者保留了一个函数是get_video_by_id，主要是通过aweme_id获取视频详情。返回的结果可以通过res.get('aweme_detail', {}).get('video', {}).get('download_addr', {}).get('url_list', [])获取视频地址列表，列表中找到[http://v3-web.douyinvod.com 开头的直接请求就可以下载了（这部分需要自己实现）。小红书暂时不清楚。

**Comment by Acyhin7x** [comment]
> > 我本意是想说下载视频，比如是否能够爬取到关键词相关的视频链接列表呢。爬取视频列表是指的什么呢？是说视频的评论信息吗。但是我看代码中主要实现的是爬取笔记和爬取笔记的评论两个基准类。
> 
> 抖音下载视频作者保留了一个函数是get_video_by_id，主要是通过aweme_id获取视频详情。返回的结果可以通过res.get('aweme_detail', {}).get('video', {}).get('download_addr', {}).get('url_list', [])获取视频地址列表，列表中找到[http://v3-web.douyinvod.com 开头的直接请求就可以下载了（这部分需要自己实现）。小红书暂时不清楚。

大佬，有抖音下载视频的代码吗，要怎么修改呢，实现了吗
