### ISSUE TITLE
针对某账号爬虫/ 无需爬取评论

### ISSUE THREAD

**Issue by Dav1cl0521** [NanmiCoder/MediaCrawler#54]
请问有方法可以针对某账号爬虫或关闭爬取评论吗？

**Comment by jeff-zzzz** [comment]
同问，能否对某个账号主页或者某个笔记页面来进行抓取？

**Comment by NanmiCoder** [comment]
这个比较实现，大家自行去 web 页面抓也请求包，根据仓库的代码改一下就好了<br>
这个仓库提供了一个基础的架子，大家基于这个架子去做自定义拓展就好了。
