### ISSUE TITLE
dy数据爬取失败

### ISSUE THREAD

**Issue by ZephaniaP** [NanmiCoder/MediaCrawler#56]
qrcode与cookie模式皆报错，报错信息如图
![baocuo](https://github.com/NanmiCoder/MediaCrawler/assets/19641519/20e7af4c-ed47-4905-9447-ee5c0a696a5f)

**Comment by vico1118** [comment]
> qrcode与cookie模式皆报错，报错信息如图 ![baocuo](https://user-images.githubusercontent.com/19641519/273380298-20e7af4c-ed47-4905-9447-ee5c0a696a5f.png)

headers["Cookie"] = "s_v_web_id=verify_leytkxgn_kvO5kOmO_SdMs_4t1o_B5ml_BUqtWM1mP6BF;" 把这句话注释掉实测可以

**Comment by vico1118** [comment]
headers["Cookie"] = "s_v_web_id=verify_leytkxgn_kvO5kOmO_SdMs_4t1o_B5ml_BUqtWM1mP6BF;" 把这句话注释掉实测可以

**Comment by ZiningWangPKU** [comment]
Install node.js will help fix it.
Restart after installation to ensure the completeness.
