### ISSUE TITLE
获取着获取着会卡住，不知道为什么，另外爬取数据会写到指定文件吗？

### ISSUE THREAD

**Issue by XksA-me** [NanmiCoder/MediaCrawler#6]
<img width="1235" alt="image" src="https://github.com/NanmiCoder/MediaCrawler/assets/43670614/a5953b38-9acb-4ba4-8a76-9c29e213a0ff">

很好用，谢谢大佬～期待贡献

**Comment by XksA-me** [comment]
运行指令：
```bash
python main.py --platform xhs --keywords 艺术二维码 --lt qrcode
Start scanning QR code to log in to Xiaohongshu. ...
waiting for scan code login, remaining time is 20s
Login successful then wait for 5 seconds redirect ...
Begin search xiaohongshu keywords
update note: {'note_id': '647eaf4900000000270038a8', 'type': 'normal', 'title': '听说小红书不让发二维码？', 'desc': '看到一篇大佬的毕业论文用AI生成隐藏二维码，这里立马操作试试水。在使用
```

**Comment by NanmiCoder** [comment]
卡住的情况你需要看下是否已经抓取完成了，如果抓取完成了程序中会一直阻塞, 具体的代码如下：https://github.com/NanmiCoder/MediaCrawler/blob/a34b6c13b476e704308c92488e9f434ab7a97fea/media_platform/xhs/core.py#L84-L87

另外，爬虫的数据写到文件的功能会完成的，只不过先会把抖音的基本流程完成之后，再完成其他的feature

**Comment by XksA-me** [comment]
谢谢大佬回复 我研究下
