### ISSUE TITLE
是否支持将文章的地址给提出来

### ISSUE THREAD

**Issue by beckguan** [NanmiCoder/MediaCrawler#63]
爬虫后的文章没有链接，可以点击链接返回到源文章

**Comment by NanmiCoder** [comment]
已支持，请更新代码～

**Comment by beckguan** [comment]
谢谢，文章地址提取存在一点bug，有的时候文章后面没地址：加了个判断才行

**Comment by NanmiCoder** [comment]
方便把修改的地方贴出来吗，我完善下代码逻辑，感谢～

**Comment by beckguan** [comment]
async def update_xhs_note(note_item: Dict):
    note_id = note_item.get("note_id")
    user_info = note_item.get("user", {})
    interact_info = note_item.get("interact_info", {})
    image_list: List[Dict] = note_item.get("image_list", [])
    note_url = "https://www.xiaohongshu.com/explore/"
    if not note_id:
        note_url = "https://www.xiaohongshu.com/explore/"
    else:
        note_url = "https://www.xiaohongshu.com/explore/" + note_id

    local_db_item = {
        "note_id": note_item.get("note_id"),
        "type": note_item.get("type"),
        "title": note_item.get("title") or note_item.get("desc", "")[:255],
        "desc": note_item.get("desc", ""),
        "creat_time": utils.get_timestamp(note_item.get("time")),
        # "time": utils.get_current_timestamp(),
        # "last_update_time": note_item.get("last_update_time", 0),
        # "last_update_time": utils.get_current_timestamp(),
        "user_id": user_info.get("user_id"),
        "nickname": user_info.get("nickname"),
        "avatar": user_info.get("avatar"),
        "liked_count": interact_info.get("liked_count"),
        "collected_count": interact_info.get("collected_count"),
        "comment_count": interact_info.get("comment_count"),
        "share_count": interact_info.get("share_count"),
        "ip_location": note_item.get("ip_location", ""),
        "image_list": ','.join([img.get('url', '') for img in image_list]),
        # "last_modify_ts": utils.get_current_timestamp(),
        # "note_url": f"https://www.xiaohongshu.com/explore/{note_id}"
        "note_url": note_url
