### ISSUE TITLE
作者您好，请问如何控制爬取的速率，感觉有点快，基本上爬50条就TimeoutError、httpcore.ConnectTimeout、httpx.ConnectTimeout了555

### ISSUE THREAD

**Issue by Alanhahaer** [NanmiCoder/MediaCrawler#65]

**Comment by NanmiCoder** [comment]
配置文件中有一个变量控制并发数量，根据自己的需求修改即可
https://github.com/NanmiCoder/MediaCrawler/blob/68c7139dd00f15bbf5fead4cce3e441955db982b/config/base_config.py#L25-L26

**Comment by Alanhahaer** [comment]
请问是加到这里吗？
<img width="496" alt="13dd7836ada17c4e25803de9aaff56d" src="https://github.com/NanmiCoder/MediaCrawler/assets/127461762/dc946aba-8bc2-43ed-9a81-7dffa2f24724">

我加了之后出现这样的问题

**Comment by Alanhahaer** [comment]
请问是加到这里吗？

**Comment by Alanhahaer** [comment]
请问是加到这里吗？
<img width="496" alt="13dd7836ada17c4e25803de9aaff56d" src="https://github.com/NanmiCoder/MediaCrawler/assets/127461762/29da5c8b-dc3f-4b92-9d44-de568e3a947c">
我加了后出现了下面的问题，不知道是不是改了导致的问题?
<img width="724" alt="011f6851a94c63b0c1bb9a2aa04d74f" src="https://github.com/NanmiCoder/MediaCrawler/assets/127461762/f19361c7-74cd-44e6-b329-7a49483a096a">

**Comment by NanmiCoder** [comment]
错误应该不是你加的sleep导致的，话说我这边的账号10个并发也没出现超时，感觉是你账号问题，导致的超时
