### ISSUE TITLE
【小红书】短信验证失败

### ISSUE THREAD

**Issue by jerryyxu** [NanmiCoder/MediaCrawler#67]
你好，小红书短信验证接口返回成功的数据，但是http状态码为 471，并且也没有收到短信，请问有遇到吗，知道是什么问题吗？

<img width="1489" alt="image" src="https://github.com/NanmiCoder/MediaCrawler/assets/8581684/6a4e6361-4af8-455c-a3d0-76725ba5292d">

**Comment by NanmiCoder** [comment]
我这边测试使用仓库里的代码手机号登录是好的，你这种情况没有遇到过
