### ISSUE TITLE
如何爬取指定笔记的评论以及IP以及评论人小红书号

### ISSUE THREAD

**Issue by bayesyf** [NanmiCoder/MediaCrawler#68]
产品需要定向地域，请问可以做到吗。还是我自己在配置参数里面改一下就可以，还是说不能指定笔记只能爬取所有笔记？

**Comment by NanmiCoder** [comment]
需要自行拓展实现，本仓库提供了是一个架子，打通请求的方法，定制化需求需要自行实现

**Comment by NanmiCoder** [comment]
已经实现，请更新代码到最新版本
