### ISSUE TITLE
我这边想抓取抖音，怎么扫完码还提示要验证码，然后没有地方可以输入验证码，程序就直接退出了

### ISSUE THREAD

**Issue by very-man** [NanmiCoder/MediaCrawler#69]

**Comment by NanmiCoder** [comment]
<img width="1539" alt="image" src="https://github.com/NanmiCoder/MediaCrawler/assets/47178017/efeb7b11-b0be-400c-8cb9-52adbb86801b">
我这边测试是可以，请排除自己账号风控问题。

**Comment by Tangsonghuai** [comment]
哈喽，请问你这边爬取抖音成功了嘛
