### ISSUE TITLE
请问短时间内同一个账号能获取多少数据

### ISSUE THREAD

**Issue by AnnoymousBear** [NanmiCoder/MediaCrawler#7]
感谢作者的repo，很好用！

我在获取的时候同一个账号在短时间内没法获取太多的数据，换IP也不行，请问作者存在这种情况吗，需要怎么样解决。

**Comment by NanmiCoder** [comment]
这个问题不在该仓库讨论的范畴~，另外请勿大规模对平台方发起爬虫请求（违法的事情咱不做哈）

**Comment by AnnoymousBear** [comment]
好的，谢谢您的回复，只做学习讨论使用。
