### ISSUE TITLE
你好，我这边爬取小红书可以，爬取抖音的话就会报错js问题

### ISSUE THREAD

**Issue by Tangsonghuai** [NanmiCoder/MediaCrawler#70]
<img width="1342" alt="截屏2023-11-13 上午9 28 53" src="https://github.com/NanmiCoder/MediaCrawler/assets/34538205/a6ab6202-6598-458f-8b92-25d389bafe54">

**Comment by Tangsonghuai** [comment]
应该是js文件出现了问题

**Comment by NanmiCoder** [comment]
看下是不是 node 版本问题，我这边的版本是：v16.8.0

**Comment by Tangsonghuai** [comment]
> 看下是不是 node 版本问题，我这边的版本是：v16.8.0

thank，问题解决
