### ISSUE TITLE
使用cookies是否可以不重复登录

### ISSUE THREAD

**Issue by AnnoymousBear** [NanmiCoder/MediaCrawler#8]
您好，在爬取小红书时，我尝试在第一次中使用QRcode登录并且获得到cookies，后续尝试使用获得到的cookies免登陆但是失败了，请问是我的操作有问题，还是免登录的上下文环境不止cookies呢，或者是其他原因？

**Comment by NanmiCoder** [comment]
对的。操作有问题，看下config中对于小红书cookie的描述~

**Comment by AnnoymousBear** [comment]
谢谢作者，是后面缺了个分号。
