### ISSUE TITLE
执行的时候出现了错误：'JS_MD5_NO_COMMON_JS

### ISSUE THREAD

**Issue by hulonghua-devin** [NanmiCoder/MediaCrawler#81]
执行的时候出现了错误：execjs._exceptions.ProgramError: TypeError: Cannot read property 'JS_MD5_NO_COMMON_JS' of null
<img width="1013" alt="image" src="https://github.com/NanmiCoder/MediaCrawler/assets/127592578/81e2ce5b-b8fc-41b7-9dde-8ad2fbf13120">
请大佬帮忙解答一下

**Comment by NanmiCoder** [comment]
安装 nodejs 环境试试，版本为：`v16.8.0`

**Comment by qiuxiaori** [comment]
版本 18 不行吗
