### ISSUE TITLE
请问这个问题怎么解决？

### ISSUE THREAD

**Issue by StevenceTanKe** [NanmiCoder/MediaCrawler#83]
<img width="790" alt="co5x5iThEN" src="https://github.com/NanmiCoder/MediaCrawler/assets/100345436/a2718d2c-a602-4520-9d1a-462ab57eb8c2">

**Comment by StevenceTanKe** [comment]
爬到最后，会出现爬不到的情况。
![image](https://github.com/NanmiCoder/MediaCrawler/assets/100345436/a81a3fc9-2d89-4b5c-9b0a-dc82dad8a213)

**Comment by NanmiCoder** [comment]
是先获取到数据之后然后报错的吗

**Comment by StevenceTanKe** [comment]
第一个是刚开始尝试，爬了几次后出现报错提示；
第二个是是将CRAWLER_MAX_NOTES_COUNT设置成500，尝试爬了几次之后，会先获取到数据然后报错。
还有个问题就是，将CRAWLER_MAX_NOTES_COUNT设置成多少比较合适？一次性爬到后面会出现程序“罢工”的情况，但是分开爬几次又会因为小红书的笔记搜索机制而大部分重复。
望解答，谢谢。

**Comment by StevenceTanKe** [comment]
谢谢

> 1、登录如果长时间不出现二维码尝试删除项目根目录下的 browser_data 目录 2、CRAWLER_MAX_NOTES_COUNT 这个的数量是不确定的，跟小红书的风控机制严格挂钩（账号级别），另外如果频繁用一个账号，会被小红书封号。

谢谢。  如果要爬取几千个笔记，有没有什么好的解决方案吗？

**Comment by NanmiCoder** [comment]
账号池
