### ISSUE TITLE
大佬,有讨论群吗?我太小白了,readme对我而言太简洁了

### ISSUE THREAD

**Issue by Minry** [NanmiCoder/MediaCrawler#9]

**Comment by Minry** [comment]
https://github.com/zhanymkanov/fastapi_production_template/pull/10
我启动不了是因为这个包
这个包已经被遗弃了

**Comment by NanmiCoder** [comment]
如果你是 python3.11 的话，aioredis 确实是不支持的，因为我这项目开发的时候我 py 版本是 3.8.3，后续我会将 aioredis 的依赖更换为 redis 库实现，提升兼容性。鉴于你目前项目启动不了，我建议你将本项目中涉及 使用 aioredis的地方都移除掉（只有手机号+验证码登录的情况下是必须的）
