### ISSUE TITLE
你好，mysql数据表的建表ddl能发一下不

### ISSUE THREAD

**Issue by zhangfang2741** [NanmiCoder/MediaCrawler#92]
你好，mysql数据表的建表ddl能发一下不

**Comment by NanmiCoder** [comment]
https://github.com/NanmiCoder/MediaCrawler/blob/5c42076ff8d0b11c7a6a70f4b5b40c72b0b35014/config/db_config.py#L8-L9

在上面的代码中，填写你 mysql 的密码，然后执行 python3 db.py 就能自动建表了
