### ISSUE TITLE
抖音评论

### ISSUE THREAD

**Issue by dfinity-web3** [NanmiCoder/MediaCrawler#95]
对于某个视频的评论，可以抓取对于这个评论的回复评论吗？

**Comment by NanmiCoder** [comment]
回复的评论暂时没去实现，目前是一级评论

**Comment by NanmiCoder** [comment]
> > 回复的评论暂时没去实现，目前是一级评论
> 
> 可以爬取商家的评论吗

当前仓库没计划支持商家的评论哦

**Comment by jinmengmeng11** [comment]
你好，可以根据视频链接抓取视频用户的信息吗？
