### ISSUE TITLE
最新代码，小红书扫码之后，手机上显示登录成功，但是终端没有登录成功的提示，过20s之后自动结束

### ISSUE THREAD

**Issue by WenmuZhou** [NanmiCoder/MediaCrawler#97]

**Comment by NanmiCoder** [comment]
通过 playwright 注入 stealth.min.js 也能被检测到自动化特征了，现在小红书登录的时候二维码扫成功之后还会有一个滑块验证，目前还没办法去过掉它，如果看到控制台有以下的字符输出，请手动处理滑动验证码
<img width="1018" alt="image" src="https://github.com/NanmiCoder/MediaCrawler/assets/47178017/727b2ca7-f711-4a32-8bf3-07673540241c">

**Comment by WenmuZhou** [comment]
谢谢，已解决

**Comment by sonumb-z** [comment]
> 通过 playwright 注入 stealth.min.js 也能被检测到自动化特征了，现在小红书登录的时候二维码扫成功之后还会有一个滑块验证，目前还没办法去过掉它，如果看到控制台有以下的字符输出，请手动处理滑动验证码 <img alt="image" width="1018" src="https://private-user-images.githubusercontent.com/47178017/290875192-727b2ca7-f711-4a32-8bf3-07673540241c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTc5OTEsIm5iZiI6MTcwNTMxNzY5MSwicGF0aCI6Ii80NzE3ODAxNy8yOTA4NzUxOTItNzI3YjJjYTctZjcxMS00YTMyLThiZjMtMDc2NzM1NDAyNDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDExMjEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NzZkMDcxYTQ2NjhlMTEyYTNhYTA4YzYyYWQ0OGU3NDU2ZDlmMzljMTU5YmIxMWVkZjA3NTk4NWFiMzk5NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.10kHnnIB4LPU3dMCuwvhH6Enivvx8DVtNHu4qrUJ1bA">

但是手机上没有显示这个滑动验证码，该怎么处理
